### ISSUE TITLE
Add support for Bitcoin Wallet for Android spending PINs

### ISSUE THREAD

**Issue by gurnec** [gurnec/btcrecover#10]
Recovery of the password of an encrypted backup is supported. Recovery of a spending PIN of the wallet file itself is also supported (but you need a rooted phone to get that wallet file).

What's not yet supported is recovery of a spending PIN inside an encrypted backup (where you know the password of the encrypted backup). If you're not rooted, this would be the only way to recover a spending PIN.

@YahyaB this might help you with schildbach/bitcoin-wallet#216, once added.

**Comment by YahyaB** [comment]
Thank you very much for the response :-)
I will test it and post a reply this days.
Cheers

**Comment by gurnec** [comment]
@YahyaB Unless you're rooted and can extract the wallet file directly from your phone, btcrecover won't work yet. I should have an update which fixes this sometime today.

**Comment by gurnec** [comment]
@YahyaB the just uploaded version adds support for spending PINs. To use it, take the two lines below and save them to a file named `btcrecover-tokens-auto.txt` in the same directory as `btcrecover.py`:

```
#--wallet android-wallet.dat --android-pin --autosave up-to-six-digits.sav
%1,6d
```

Then follow the instructions in the [Quick Start](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#btcrecover-tutorial). (Your wallet backup file must be in that same directory, and it must be named `android-wallet.dat`.)

**Comment by errrrc** [comment]
im getting a message of "can't find an scrypt library performance will be severely degraded" then it can't run because the max eta is over 168 hours with a 6 digit pin.

**Comment by CoreDuxter** [comment]
Hy guy's I'm new here and have the same issue like allready discuss in #33 i forgot my spending pin :( Now my problem is that i need extreamly long to decode, same issue like above from errrrc i receive the same message and need 8minits for 1digit! is there any thin i do wrong? here wat I'm typing in:

in the tokens.txt I have just: %0,1d

btcrecover.py --wallet wallet --tokenlist tokens.txt --android-pin
btcrecover.py: warning: terminal does not support UTF; passwords with non-ASCII chars might not work
Please enter the password for the Bitcoin Wallet for Android/BlackBerry backup:
btcrecover.py: warning: can't find an scrypt library, performance will be severely degraded
Wallet difficulty: scrypt N, r, p = 65536, 8, 1
Using 8 worker threads
11 of 11 [##########################################################] 0:08:21,
Password search exhausted

Hope someone can help me.
Thank you!

**Comment by CoreDuxter** [comment]
Hi Christopher


I'm trying sinse 4 days every evening to find my password without succsess and didn't have a lot of sleep the last days.
I think I was to tired to see what I was doing while installing all the different things. That I have skipped the script instalation.
I only installed Python 2.7, Google protobuf, and PyCrypto on my windows 10 x64

after checking the libsodium version, that didn't work, I checked the instructions again and saw my mistake. thank you for helping me now everything works. after reciving your mail everything was clear why it coudn't work, and installed the libsodium script.
i now hope my spend key isn't too long and its possible to find it... My CPU will work now for me :)
I'll give you feedback if it will work.

If it works i would like to donate you something for your support.

you will here from me.
thanks a lot...

regards
Thomas



________________________________
Von: Christopher Gurnee <notifications@github.com>
Gesendet: Donnerstag, 20. Juli 2017 02:17
An: gurnec/btcrecover
Cc: CoreDuxter; Comment
Betreff: Re: [gurnec/btcrecover] Add support for Bitcoin Wallet for Android spending PINs (#10)


Which OS are you running on? I'll assume Windows for now...

Most of the time this happens when you install the 32-bit version of Python and the 64-bit version of libsodium (scrypt), or vice versa, or a mismatching version (again 32 vs. 64-bit) of the Microsoft Visual C++ libraries.

Did you follow the instructions to install scrypt on Windows<https://github.com/gurnec/btcrecover/blob/master/docs/INSTALL.md#windows-3> (I'm guessing you did)?

Could you run this command post the results?

python -c "import ctypes.util;p=ctypes.util.find_library('libsodium');print p;print repr(ctypes.CDLL(p))"


Thanks!

**Comment by gurnec** [comment]
I"m glad you got it working, good luck!

**Comment by QLadry** [comment]
@CoreDuxter how did you install the libsodium? 

I've copied it to the directory of Python27, but what to do next? 
I get the same error: C:\btcrecover>C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist quincy.txt --android-pin
Starting btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
btcrecover.py: warning: terminal does not support UTF; passwords with non-ASCII chars might not work
(note your password will not be displayed as you type)
Please enter the password for the Bitcoin Wallet for Android/BlackBerry backup:
btcrecover.py: warning: can't find an scrypt library, performance will be severely degraded
Wallet difficulty: scrypt N, r, p = 65536, 8, 1

If you could help I would really appreciate it :)

**Comment by QLadry** [comment]
@gurnec Maybe you know the answer as well?

**Comment by mathuvelie** [comment]
Hi, new to programming. Forgot spending pin...success!

Comment: 
I was new to programming, so it took me awhile with trial and error.  I was about to post on this site a list of everything I had installed and done so far, so someone might be able to help me trouble-shoot, and was part-way through typing "(note your password will not be displayed as you type)" (I thought something was wrong that I couldn't see the characters type, like a missing file or driver) until I realized my error. So, I tried again, typed in the backup password, waited for ~25 min, tried the password on bitcoin app, and it worked!

I found it helpful reading gurnec's response to @YahyaB on Mar 30, 2015; even though I read through the reading, I didn't know how to compose the btcrecover-tokens-auto.txt (with order of all the "--" commands and such), and I thought having it spelled out really helped:
"
@YahyaB the just uploaded version adds support for spending PINs. To use it, take the two lines below and save them to a file named btcrecover-tokens-auto.txt in the same directory as btcrecover.py:

#--wallet android-wallet.dat --android-pin --autosave up-to-six-digits.sav
%1,6d
Then follow the instructions in the Quick Start. (Your wallet backup file must be in that same directory, and it must be named android-wallet.dat.)
"

So, I followed the instructions installing Python 2.7.14, scrypt, Google protobuf, Pycrypto, and the other steps, (and observing that your backup wallet password doesn't show after double clicking btcrecover.py), typed in the backup password, and it worked. Basically I'm saying that it helped me to have the exact process spelled out, for non-programmers. (They can still contribute bit coin)

What I used in the "btcrecover-tokens-auto.txt" file, in the same folder as the btcrecover.py file, that worked for me is below, as I had a hunch that mine was a four digit pin. I also used a one letter backup wallet password, which may have helped prevent typos for the process.
"
 #--wallet android-wallet.dat --android-pin --autosave up-to-six-digits.sav --pause
%1,4d
"

Questions:
1
I'd like to contribute to this project, but does the address change after using it once/is this address to send still current, and if I send it to this address, will it get to you? 
"If you find btcrecover helpful, please consider a small donation to help support my efforts: 3Au8ZodNHPei7MQiSVAWb7NB2yqsb48GW4"

2
Is only changing the spending pin (and this time writing it down somewhere and remembering it) after you recover the 'lost' one through this process sufficient, or is it best to change wallets entirely?

Thank-you for your help and contributing to this project,
renewenergy

**Comment by EddyEddyEddyEddy** [comment]
Anyone can help with spending PIN , how to recover ?

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by DoganM95** [comment]
> Recovery of the password of an encrypted backup is supported. Recovery of a spending PIN of the wallet file itself is also supported (but you need a rooted phone to get that wallet file).
> 
> What's not yet supported is recovery of a spending PIN inside an encrypted backup (where you know the password of the encrypted backup). If you're not rooted, this would be the only way to recover a spending PIN.
> 
> @YahyaB this might help you with schildbach/bitcoin-wallet#216, once added.


@gurnec How to get the forgotten spending pin (of Schildenbach BTC Wallet) on a rooted device? Can't find anything on that using google..
