### ISSUE TITLE
global name 'cl_kernel' is not defined

### ISSUE THREAD

**Issue by langerhans** [gurnec/btcrecover#11]
Hi, running btcrecover on Windows kept giving me following error:

```
C:\Python27\python.exe btcrecover.py --wallet wallet.dat --performance --enable-gpu --global-ws 4096 --local-ws 512
--gpu-names #2
Traceback (most recent call last):
  File "btcrecover.py", line 4859, in <module>
    parse_arguments(sys.argv[1:])
  File "btcrecover.py", line 2904, in parse_arguments
    loaded_wallet.init_opencl_kernel(devices, args.global_ws, args.local_ws, args.int_rate, *extra_opencl_args)
  File "btcrecover.py", line 751, in init_opencl_kernel
    max_local_ws = cl_kernel.get_work_group_info(pyopencl.kernel_work_group_info.WORK_GROUP_SIZE, device)
NameError: global name 'cl_kernel' is not defined
```

So I changed in line 721 `cl_kernel.get_work_group_info` to `self._cl_kernel.get_work_group_info`

Is that an issue or am I just doing something wrong? Cause after my change it seems to work fine.

**Comment by gurnec** [comment]
It looks like I introduced this bug a few months ago in v0.12.0, and never noticed it... that's embarrassing....

I'll apply your fix ASAP. This bug only rears its ugly head when the `--local-ws` option is used, and the unit tests don't use it. I'll update the unit tests to use this option at the same time.

Thanks for catching this!!

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
