### ISSUE TITLE
Set Min # Map Typos for Leetspeak

### ISSUE THREAD

**Issue by asparagusking** [gurnec/btcrecover#112]
I'm pretty sure I know my passphrase but I can't remember the extent to which I used leetspeak. I'd like to test a range of numbers of substitutions, e.g. 14-23, instead of testing the cases of 1,2,3...13 substitutions. However, I can't get the program to run specifying --min-typos 14 and --typos 23 or --typos-max-map 23. I pasted my failed commands below. Any advice?

--listpass --tokenlist tokens.txt  --typos-map leets.txt --typos 23 --min-typos 14 | more
--listpass --tokenlist tokens.txt  --typos-map leets.txt --typos-max-map 23 --min-typos 14 | more

**Comment by gurnec** [comment]
The `--min-typos` option gets quite slow with a large minimum count like yours, it just wasn't implemented as well as it could have been... I'll see if I can improve this.

**Comment by gurnec** [comment]
I just uploaded a new version, can you let me know if it's working for you now?

**Comment by asparagusking** [comment]
I found a work around: I put the most likely leetspeak variants of the
passphrase components directly into the token file. I'm running a large
batch now, but once it's through I'll try your new code.

**Comment by asparagusking** [comment]
Hi Christopher,

I ended up finding my passphrase without that functionality. I sent you a
small BTC donation. Thanks for putting together this program!

Cheers,
Jon

**Comment by gurnec** [comment]
Thanks, Jon, it's much appreciated! I'm glad things worked out!
