### ISSUE TITLE
support for BIP-32/39/44 where SEED is known but password has typo

### ISSUE THREAD

**Issue by techmarketing** [gurnec/btcrecover#12]
Seeking support for BIP-32/39/44 use case where person has full correct seed, however has made a typo in the password used.  In this particular instance it's regarding the trezor. The trezor supports/allows you to type any password and it will generate bitcoin addresses based on that password. If password is mispelled or typo it will still produce addresses. 
In this example I have 2 addresses generated with wrong password, and the password (however there is a typo).  

Excellent software and instructions and was able to get seedrecover.py working, however in tutorial did not see this capability and in wizard was not able to see how typo password could be resolved. 
Apologies if this is the wrong area to submit this but wasn't sure what other way to ask this/communicate with Gurnec.

**Comment by gurnec** [comment]
You're right, there's currently no support for trying to find a lost BIP-39 password given a known seed and an mpk or address, and it *would* be useful to have this. I'll give it some thought....

FYI it would almost certainly be added to btcrecover.py, not to seedrecover.py, so you'd need to read/understand the [main btcrecover tutorial](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md) in order to use it (once/if I can add it).

**Comment by techmarketing** [comment]
Thanks for the response and explanation. Wish I could help out more, but my python skills are lacking. I know there is some demand as I see others with similar issue.  
https://www.reddit.com/r/Bitcoin/comments/2xqewu/trezor_passphrase_recovery_10_bounty/  
Myself I lost a significant amount of btc due to typo.   I will follow this. In the meantime perhaps the python script I came across here would be helpful to you as they are the closest I found to something where seed and pass could be piped in to output addresses:  
http://blog.bitbargain.com/post/97938486492/trezor  
![20-06-2015 08 37 26](https://cloud.githubusercontent.com/assets/8548156/8267280/1e58e67c-1728-11e5-930a-b5cd5c7136bb.png)

**Comment by gurnec** [comment]
FYI I have an alpha-grade version I'm in the process of testing and cleaning up, and it seems to be mostly working. It'll probably be a few more days before I can find the time to finish this up... just hang in there, it is coming.

**Comment by techmarketing** [comment]
You are awesome! Thank you sir.

**Comment by gurnec** [comment]
@techmarketing, I just uploaded a version of btcrecover.py with BIP-39 passhprase support. There's some new (albeit terse) documentation for it here: <https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#bip-39-passphrases>

Could you let me know how it works out, either way? (And of course if you have any questions, feel free to ask!)

Thanks.

**Comment by techmarketing** [comment]
That is amazing. I will try it out first thing tomorrow against known addresses and 100% known passwords and will report back those results first. 
Then I will try it against the address I am having the typo with and run that for a few days and let you know for sure!

**Comment by techmarketing** [comment]
Update: My testing validated that given a known seed and known 2nd address your btcrecover was able to find the password for the trezor, so great work! 
That was just a test address with simple password. Now I will go on to try it on my real address with known typo password and known seed -  will run that for a few days etc and try many more things. Best Regards

**Comment by gurnec** [comment]
Thanks for the update, and good luck!
-Chris

**Comment by techmarketing** [comment]
Amazing piece of software!  
I have made a donation to you!  I went through documentation but was very tired so did not fully understand everything but thought I better kick off something before I went to bed. Your software is very fast - and perhaps the trezor BIP isn't as secure as other?  I guess it can try many passwords per second vs other types. I mean of course trezor is secure due to seed - just thinking your software is very good and fast even with just a laptop.   
I kicked it off and stood up to go to bed and leave it run overnight.  To my gaping jaw in 15 seconds flat it reported the password was found. I had made a simple typo and reversed 2 letters. But never would have figured it out as I tried 50 passwords and typos manually already. In 15 sec it had tried 3500 passwords and found it.   It was going to take only 13min to try 195000 passwords.  
All I can say is you are a master!

**Comment by gurnec** [comment]
That's great, I'm glad you found it! **Thank you so much** for your donation and your kind words (not to mention your patience)!

> Your software is very fast - and perhaps the trezor BIP isn't as secure as other? I guess it can try many passwords per second vs other types.

BIP-39 passphrases are OK (not terrible) when it comes to comparing the [key stretching](https://en.wikipedia.org/wiki/Key_stretching) of various wallets. Here's a spreadsheet that I maintain comparing the passwords-per-second guess rates which btcrecover and [John the Ripper](https://github.com/magnumripper/JohnTheRipper) are capable of for different wallets: <http://1drv.ms/1pnpk0m>

You'll see BIP-39 falls somewhere in the middle (and it's *much* better than the worst wallets). To be fair though, if it were GPU-accelerated I'm sure it'd be a decent bit faster.

**Comment by AbdulaOblongata** [comment]
Hi, I've just come across this thread looking for help trying to recover a BIP39 key where I do not have the passphrase.  This thread looked like you needed part of the passphrase but is it possible to run with randomly generated passphrases.  I realize it my take a while but if recoverable the resources invested into such a solution would be worth it.  Any help would be greatly appreciated.
Regards,
Jonathan

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
