### ISSUE TITLE
Need help with 1080 ti config and build tokens file

### ISSUE THREAD

**Issue by Chococat** [gurnec/btcrecover#129]
Hi Gurnec,

Sorry to bump this topic up, can you help me abit.

1. I'm using one 1080 Ti to find my Vertcoin password, I tried many --global-ws and --local-ws 
parameter but only get highest to 15kP/s, is that normal? Because my GPU won't load 100% all the time, it load 100% then stop, then load... As you can see in photo below:

https://imgur.com/vFlkqP6

2. Can you help me build an optimize tokens file with info below: (I'm sorry, I'm Vietnamese and I have limited on English skill, so it's hard for me to build optimize tokens files).

2.1 Best case scenario (this is my running tokens file right now, with everything I can remember):

> %i[t]ra%i[c]hanh %i[t]ra.%i[c]hanh %i[t]ra..%i[c]hanh %i[v]ethed %i[h]a%i[n]oi%i[c]omputer %i[h]a%i[n]oi%i[c]omputer.com %i[h]a%i[n]oi%i[c]omputer.vn %i[c]hanh%i[m]uoi %i[c]hanh.%i[m]uoi %i[c]hanh..%i[m]uoi %i[m]inh%i[k]hai 
> 2101 44099 444099 4492 1012 66099 627
> %i[v]ethed
> %i[w]allet
> !
> .
> *
> #
> @
> ?
> %%
> %s
> %s

2.2 Bad case scenario:
With all characters in 2.1 but they may switch because of my typos.

2.3 Worst case scenario (if 2.1 and 2.2 cant find any match):

- Include max 4 lower or uppercase letters (min 2, max 4)
- Include max 16 lowercase letters. (min 10, max 16)
- Include max 5 digit (min 4, max 5)
- Include following special characters: . ! @ # % * "space" ( "space" and . -dot- may stay random, but ! @ # % only stay at first or last of password).
- May include or not: .Wallet or .wallet

Password may look like this: !Hotel.California55055.Wallet*#@?
Or Hotel.California@.

Edit: I forget, I may get 10 or more 1080 Ti to get my password back, that will make 3 to 4 rigs, how can I combine 4 rigs as one to crack my password? and can I use cloud base hash like Nicehash to crack my password?

3. If I'm using 2 VGA to crack password, my command will look like this:

python btcrecover.py --wallet wallet.dat --enable-gpu --gpu-names 1 2 --global-ws 200704 199680 --local-ws 1024 --tokenlist tokens.txt --no-dupchecks --no-eta --max-tokens 12 

But if I want to stop, and only use 2nd VGA to crack password, my command line will look like this:

python btcrecover.py --wallet wallet.dat --enable-gpu --gpu-names 2 --global-ws 200704 --local-ws 1024 --tokenlist tokens.txt --no-dupchecks --no-eta --max-tokens 12 --skip 123456789

I just wonder in this case, if my tokens file stay the same, and I use 2nd VGA to start from 123456789 password, will all combine stay the same? and its ok to do like this or if I changed only VGA in command line, I have to start search from beginning?

OR if I use savefile, how can I switch VGA and still can use process from savefile to keep searching without start from beginning?

Thank you very much.

**Comment by gurnec** [comment]
> but only get highest to 15kP/s, is that normal?

I'd say that's quite good for a single GPU, much better than my poor old R9 390.

> my GPU won't load 100% all the time, it load 100% then stop, then load

That's expected behavior, it's a limitation on the way I wrote it (the OpenCL-driving code isn't pipelined well). You can get a few extra percent performance if you separate it into two processes, one to generate passwords, and one to test them (although `--no-eta` is forced on and you can't use `--autosave`, so it may not be worth it):

    python btcrecover.py --listpass --tokenlist tokens.txt --no-dupchecks --max-tokens 12 | python btcrecover.py --passwordlist --wallet wallet.dat --enable-gpu --global-ws 200704 --local-ws 1024 --no-dupchecks

> I'm sorry, I'm Vietnamese and I have limited on English skill

No need to apologize, you're English is better than many native English-speakers 😃

> Can you help me build an optimize tokens file with info below

I can try, could you answer these questions?

Can both of these appear in the same password guess: `%i[v]ethed` and `%i[w]allet`?

Are there any tokens which *definitely* appear in your password?

Can you tell me anything about the order in which the tokens should appear in your password? Is something always first, or is one token always before/after another token?

I see that you added a `--max-tokens 12` option. Your tokenlist has 13 lines, and so at most 13 tokens will be added to any single guess. `--max-tokens 12` only removes guesses which have all 13 tokens; do you think the `--max-tokens` value could be lowered?

> how can I combine 4 rigs as one to crack my password?

You can use the `--worker` option. With 4 rigs, add `--worker 1/4` on the first rig, `--worker 2/4` on the second rig, etc. The more rigs and/or GPUs you have, the more advantage you'll get from using the "two-processes" approach I mentioned above (you should use the `--worker` option on *only* the first process).

> can I use cloud base hash like Nicehash to crack my password?

I'm not familiar with them, sorry. You can use AWS, [see here](https://github.com/gurnec/btcrecover/issues/95#issuecomment-325208320), however be aware: in that post I recommend Spot instances which pretty much require using `--autosave`, and `--autosave` is currently incompatible with the two-processes approach, so it might not scale as well as you'd like...

> If I'm using 2 VGA to crack password, my command will look like this ...

Yes, but be careful... specifying `--gpu-names 1 2` uses the first two *OpenCL* devices, and some *CPUs* are OpenCL devices, so you might end up using a CPU and a GPU by accident...

> if my tokens file stay the same, and I use 2nd VGA to start from 123456789 password, will all combine stay the same? and its ok to do like this

Yes (and good question!), the password order stays the same and it's safe to do this so long as no other options change.

> OR if I use savefile, how can I switch VGA and still can use process from savefile to keep searching without start from beginning?

Unfortunately you can't change which VGA card(s) you're using and still use the *same* savefile, you'd need to start a new savefile (and manually use `--skip`) each time you change the VGA cards. It's a known limitation and something I plan on fixing in the future (I actually started working on it a week or two ago), but I have no idea when it'll be done.

**Comment by Chococat** [comment]
Thank you very much for your great software and careful reply.

> I'd say that's quite good for a single GPU, much better than my poor old R9 390.

1. I did notice my performance is good compare kys86468's Just 20 kP/s with 4x1080 Ti, but with your new command line:
> python btcrecover.py --listpass --tokenlist tokens.txt --no-dupchecks --max-tokens 12 | python btcrecover.py --passwordlist --wallet wallet.dat --enable-gpu --global-ws 200704 --local-ws 1024 --no-dupchecks

2 GPUs went up from ~24 kP/s to ~27 kP/s, so nice.

2. About tokens:

2.1. Text:
2.1.1 
Vethed (V may lowcase or cap)

2.1.2
Western (W and T lowcase or cap)
WesternDigital (W T D lowcase or cap)
Western.Digital (W T D lowcase or cap)

2.1.3
ChanhMuoi (C and M may lowcase or cap)
Chanh.Muoi (C and M may lowcase or cap)
Chanh..Muoi ((C and M may lowcase or cap)
HaNoiComputer (H N C may lowcase or cap)
HaNoiComputer.com (H N C may lowcase or cap)
HaNoiComputer.vn (H N C may lowcase or cap)
TraChanh (T and C may lowcase or cap)
Tra.Chanh (T and C may lowcase or cap)
Tra..Chanh (T and C may lowcase or cap)
MinhKhai (M and K may lowcase or cap)
VTC (V T C lowcase or cap)
VertCoin (V C lowcase or cap)

- 2.1.1 may appear or not and of it appear, it combine with tokens in 2.1.2 and 2.1.3, we may have password: Vethed.VTC.ChanhMuoi or WesternChanhMuoi, but we never have Vethed.Vethed
- 2.1.2 not may apprear or not, if token appear toekn only combine with 2.1.1 and 2.1.3,  token never combine with eachother, we never have: WesternWesternDigital
- 2.1.3 not may apprear or not, if token appear toekn only combine with 2.1.1 and 2.1.2,  token never combine with eachother, we never have: ChanhMuoiTraChanh


2.2 Number:
1012

2101 
44099
444099
4492
1012
66099
627

1012  maybe appear or not, but if it appear, it combine with one of those, but all other are individual, they are not combine

For example: we may have 1012Vethed2101 or Vethed2101, but we wont have 4492Vethed44099


2.3. 
Wallet 

This maybe appear in password:

For example: we may have Vethed2101.Wallet or just Vethed2101


2.4. Special Character maybe appear:
!
.
*
#
@
?
%
%s (space)

all other special only appear once but . (dot) and  (space) may appear 2 times max

For example: we may have Vethed  ChanhMuoi@. or Vethed.ChanhMuoi.@ but we never have Vethed.ChanhMuoi@@

>Are there any tokens which definitely appear in your password?
So far I only know . (dot) definitely in password, and Wallet like 80% definitely appear in password.

> Can both of these appear in the same password guess: %i[v]ethed and %i[w]allet?
Yes, they may appear both in same password like: Vethed44099.Wallet or Vethed.ChanhMuoi.Wallet

> Can you tell me anything about the order in which the tokens should appear in your password? Is something always first, or is one token always before/after another token?
- If wallet appear, it never stay first, it only stay after 2.1, 2.2.
- ! * % ? never stay in middle, if they apprear, they only stay first or last of password.
- . (dot), %s (space), %% (%), @ they will stay random in password.

> I see that you added a --max-tokens 12 option. Your tokenlist has 13 lines, and so at most 13 tokens will be added to any single guess. --max-tokens 12 only removes guesses which have all 13 tokens; do you think the --max-tokens value could be lowered?

Its 13 lines, because . (dot) and %s (space) may appear 2 times in password.

3.
>You can use the --worker option. With 4 rigs, add --worker 1/4 on the first rig, --worker 2/4 on the second rig, etc. The more rigs and/or GPUs you have, the more advantage you'll get from using the "two-processes" approach I mentioned above (you should use the --worker option on only the first process).

Even without calculate total passwords, 4 rigs still know where to start? That really helpful <3

4.
> if my tokens file stay the same, and I use 2nd VGA to start from 123456789 password, will all combine stay the same? and its ok to do like this
> Yes (and good question!), the password order stays the same and it's safe to do this so long as no other options change.

Ya, everything stay the same (tokens file, command line..), the only thing change in command lines is 

**--gpu-names 1 2** --global-ws 200704 --local-ws 1024

To 

**--gpu-names 2** --global-ws 200704 --local-ws 1024

This is my main rig, so I need 1st GPUs to do other work sometime xD.

Have a nice weekend @gurnec

**Comment by TTN-** [comment]
>Extra question: is there anyway to speed up skipping passwords step, I lost around 24 hours to made ~2bil5 pass, but lost like ~6 hours to skips, while skipping, btcrecover only use ~10% CPU (my CPU is 3960x - 6C 12T - 4,3GHz) and didn't use any GPU.

**Comment by Chococat** [comment]
@TTN- Thanks but I'm not programmer :(

**Comment by Chococat** [comment]
@gurnec Still waiting for your help with built tokens files, if you free please help me out, thank you very much.

**Comment by gurnec** [comment]
@Chococat If you've figured out what you were looking for, then thank you for closing your issue... but if you haven't, please consider re-opening it! I'm very much guilty of prioritizing "easy" issues over more complex ones, but I still have every intention of revisiting this when I have more time to thoroughly go over everything.

**Comment by gurnec** [comment]
@Chococat OK, just saw the new issue, I can't look at it right away, but it's still on my list!

**Comment by gurnec** [comment]
> It would be nice if we can change this command with savefile.

This is something I've been working on. If you'd like to be notified once it's completed (it will probably be a while...), please open a new issue to request it and I'll update the new issue once it's done.

> is there anyway to speed up skipping passwords step

This would be extremely hard with CPython, and a lot of the other installation requirements depend on CPython. However, it may be possible with PyPy or Stackless, and there *might* be alternative libraries that will work with those. It requires more research... again, if you open a new issue for this, I'll update it if I make any progress.

**Comment by rterwedo** [comment]
@Chococat - if you know what line you stopped at, just dump that line and later to a new file, and start it from beginning (basically same as skip).

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
