### ISSUE TITLE
Feature request: Script to make token file into password list

### ISSUE THREAD

**Issue by TTN-** [gurnec/btcrecover#135]
I'd like to make a password list from a token file.

Then I can take it to other cracking programs like hashcat (which has far less powerful password list creation tools) than btcrecover does. Also it lets me see what passwords I'm actually creating and testing (to make sure I have this right) and makes it easier for new users to actually see what their token file does, since I want to see what I'm actually trying. I'd be wasting a lot of time to leave my rig running for 2 weeks if it wasn't doing it the way I thought it was.

**Comment by gurnec** [comment]
See #119, that's probably what you want.

**Comment by TTN-** [comment]
Ah, excellent. Thanks for your super fast response. Is it mentioned in the documentation? I seem to have missed it, if it is there. It may be worth adding?

**Comment by gurnec** [comment]
> Is it mentioned in the documentation?

Sort of... it's mentioned [here](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#testing-your-config), but it's not specifically mentioned how to redirect the output to a file. To be fair, that redirection feature (the `|` and `>` symbols) is part of your operating system and not btcrecover, but it would make sense to add it to the docs anyways.

**Comment by TTN-** [comment]
Thanks!!
