### ISSUE TITLE
Any way to avoid repeated adjacent characters?

### ISSUE THREAD

**Issue by levycarneiro** [gurnec/btcrecover#139]
Let's say I don't want to try passwords such as:

aaa7jr8hr5
aaa7jr8hr6
aaa7jr8hr7

..because they have 3 repeated "a"s.

Is it possible to specify that in tokens.txt?

Thanks!

**Comment by levycarneiro** [comment]
Something like:

%!1,3D => where "D"is duplicated numbers.
%!1,3E => where "E" is duplicated lowercase letters.
%!1,3F => where "F" is duplicated uppercase letters.

Where "!" is "do not have".

**Comment by deloxd** [comment]
Hi, Maybe you have found a some solution? I m wondering about that too.

**Comment by gurnec** [comment]
You can filter these out via a command line option.

To never try passwords which contain three identical characters in a row: `--regex-never "(.)\1\1"`

To never try passwords which contain two identical characters in a row: `--regex-never "(.)\1"`

Is this what you're looking for?

Note that this won't speed things up much (if any) for "fast" wallets (ones without key stretching) like Electrum (before 3.0) or MultiBit Classic.

**Comment by levycarneiro** [comment]
That's exactly what I need, thanks @gurnec!

Using this to not have 2 repeated adjacent letters:

--regex-never "([a-z])\1"

**Comment by gurnec** [comment]
You got it! (Just be aware that it's case-sensitive.)

**Comment by deloxd** [comment]
And one more question in this subject.

if I need avoid repeat all letters and numbers like [a-zA-Z0-9] ? How can i do it ?:)

**Comment by davidhekim** [comment]
Is there a way to avoid the repetition of an entire token?

**Comment by devbox** [comment]
> Is there a way to avoid the repetition of an entire token?

I´m looking for this option too! Any solution for this?
