### ISSUE TITLE
Possible to computer pwd or private key given all data on some addresses in the same wallet?

### ISSUE THREAD

**Issue by rterwedo** [gurnec/btcrecover#143]
Given we have:  

1) a wallet.dat file with ~100 addresses.
2) 40 addresses in the same wallet, with addr, pub keys, encrypted private keys AND unencrypted private keys
3) mkey with: {crypted key, salt,  and nDeriveIterations, etc)
4) Anything else we need from pywallet, etc

Is it possible to find the password for the wallet as a whole OR the unencrypted private key for one SPECIFIC address in the wallet file assuming we have the pub key, addr, and encrypted key for that address (along with mkey).

Note these are all addresses in the SAME wallet.dat, encrypted at the same time with same password and we could recover unencrypted private keys for ~40 of them (but not the 1 addr we want).

**Comment by rterwedo** [comment]
Bip38 is not subject to known plain text attacks

**Comment by gurnec** [comment]
@rterwedo You have it effectively right: AES has no known-plaintext attacks, and the private keys generated either randomly (as in earlier versions of Bitcoin Core) or deterministicly via BIP-32 hardened derivation (in more recent versions) have no known related-key attacks.

**Comment by rterwedo** [comment]
@gurnec I should have specified...  but what I was really after was "Are there more efficient algos [than btcrecover] given having all unencryp priv, encrypt priv, pub, address etc for ~1/2 the keys in a wallet"

**Comment by gurnec** [comment]
No, there's no known way. You need either the password & encrypted mkey, or the paintext mkey, neither of which you have. The other information you have (even the other plaintext privkeys you have) do not help. This is by design.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
