### ISSUE TITLE
Error extracting data.

### ISSUE THREAD

**Issue by mrmookie** [gurnec/btcrecover#15]
Following the example for a Multibit Classic Key I run into the following error and I've been unable to track it down..

>python btcrecover.py --data-extract --tokenlist ../wordlist.txt
Please enter the data from the extract script
> {entered my data from extract-script/extract-multibit-privkey.py}
btcrecover.py: error: on line 17: invalid wildcard (%) syntax (use %% to escape a %)
>

I'm using Python 2.7.9 on Debian.

**Comment by gurnec** [comment]
Sorry for the delay (and thanks for the doc fixes in your PR!).

The `%` symbol is special: in introduces a ["wildcard", see here](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#expanding-wildcards). If your password possibly has a `%`, you need to "escape" it by adding an extra `%`. For example, if you want to try `with%symbol` in the password, then in the token file (line 17 in your case) you'd place:

    with%%symbol

If you run *btcrecover.py* with `--listpass`, you'll see that the escaped `%` is "collapsed" back down to a single `%` when generating the actual passwords to try.

Hopefully this makes sense?

**Comment by RickDeckcard** [comment]
Hello, I have the same problem and then see my token.txt file. If you put symbols like % or $ then appear the error because you need put before %, for exaple %% to search the symbol %.
