### ISSUE TITLE
Need help with build the best tokens file

### ISSUE THREAD

**Issue by Chococat** [gurnec/btcrecover#152]
Hi @gurnec 

Thank you so much for made this amazing tool. like I said in other topic, I'm Vietnamese, my English limited, please help me to built a tokens file with info below, I will send you 50USD (as ETH) right after u done tokens file and if I find password for VTC wallet, I will send 500VTC (as VTC or as 
equivalent BTC, ETH), thank you.

1. Closed topic here: https://github.com/gurnec/btcrecover/issues/129

**2. About tokens information:**
**2.1. Text:**
**2.1.1**
Vethed (V may lowcase or cap)

**2.1.2**
Western (W and T lowcase or cap)
WesternDigital (W T D lowcase or cap)
Western.Digital (W T D lowcase or cap)

**2.1.3**
ChanhMuoi (C and M may lowcase or cap)
Chanh.Muoi (C and M may lowcase or cap)
Chanh..Muoi ((C and M may lowcase or cap)
HaNoiComputer (H N C may lowcase or cap)
HaNoiComputer.com (H N C may lowcase or cap)
HaNoiComputer.vn (H N C may lowcase or cap)
TraChanh (T and C may lowcase or cap)
Tra.Chanh (T and C may lowcase or cap)
Tra..Chanh (T and C may lowcase or cap)
MinhKhai (M and K may lowcase or cap)
VTC (V T C lowcase or cap)
VertCoin (V C lowcase or cap)

_2.1.1_ may appear or not and if it appear, it combine with tokens in _2.1.2_ and _2.1.3_, we may have password: Vethed.VTC.ChanhMuoi or WesternChanhMuoi, but we never have Vethed.Vethed
_2.1.2_ not may apprear or not, if token appear toekn only combine with 2.1.1 and 2.1.3, token never combine with eachother, we never have: WesternWesternDigital
_2.1.3_ not may apprear or not, if token appear toekn only combine with 2.1.1 and 2.1.2, token never combine with eachother, we never have: ChanhMuoiTraChanh

**2.2 Number:**
1012

2101
44099
444099
4492
1012
66099
627

1012 maybe appear or not, but if it appear, it combine with one of those, but all other are individual, they are not combine

For example: we may have 1012Vethed2101 or Vethed2101, but we wont have 4492Vethed44099

**2.3.**
Wallet

This maybe appear in password:

For example: we may have Vethed2101.Wallet or just Vethed2101

**2.4. Special Character maybe appear:**
!
.
*

@
?
%
%s (space)

all other special only appear once but . (dot) and (space) may appear 2 times max

For example: we may have Vethed ChanhMuoi@. or Vethed.ChanhMuoi.@ but we never have Vethed.ChanhMuoi@@

> Are there any tokens which definitely appear in your password?

So far I only know . (dot) definitely in password, and Wallet like 80% definitely appear in password.

> Can both of these appear in the same password guess: %i[v]ethed and %i[w]allet?

Yes, they may appear both in same password like: Vethed44099.Wallet or Vethed.ChanhMuoi.Wallet

> Can you tell me anything about the order in which the tokens should appear in your password? Is something always first, or is one token always before/after another token?

If wallet appear, it never stay first, it only stay after _2.1_, _2.2_.
! * % ? never stay in middle, if they apprear, they only stay first or last of password.
. (dot), %s (space), %% (%), @ they will stay random in password.

> I see that you added a --max-tokens 12 option. Your tokenlist has 13 lines, and so at most 13 tokens will be added to any single guess. --max-tokens 12 only removes guesses which have all 13 tokens; do you think the --max-tokens value could be lowered?

Its 13 lines, because . (dot) and %s (space) may appear 2 times in password.

3. Which is the best tokens file for 12 characters password (with low, uppercase, numbers)  or its impossible to find password with 12 characters right now? 

Hope to get good news from you asap, thanks.

**Comment by gurnec** [comment]
First off, could you please retract your reward? You're welcome to donate to my donation address at any time or course, but I really don't want any type of reward offers (or on the other side, soliciting for business) in any issues... (anyone can use btcrecover however they want, including for business, I just want paying business to happen elsewhere).

I've just started reading this, and I'll add comments/questions as I go through it. First one:

Above, you say:

> 2.1.1 ... we may have password: Vethed.VTC.ChanhMuoi

and just below:

> 2.1.3 ... never combine with eachother, we never have: ChanhMuoiTraChanh

`Vethed.VTC.ChanhMuoi`, which you say is valid, has *two* tokens from the 2.1.3 list (`VTC` and `ChanhMuoi`) which seems to violate the 2.1.3 rule that they "never combine with each other". Is there a mistake here?

**Comment by Chococat** [comment]
> First off, could you please retract your reward? You're welcome to donate to my donation address at any time or course, but I really don't want any type of reward offers (or on the other side, soliciting for business) in any issues... (anyone can use btcrecover however they want, including for business, I just want paying business to happen elsewhere).

I'm sorry, I mean I will donate 50$ as ETH and I will donate more 500VTC (if I find the password), I know this is free and everyone can use, I don't mean to be rude, just don't know how to explain my mind cleanly.

> Vethed.VTC.ChanhMuoi, which you say is valid, has two tokens from the 2.1.3 list (VTC and ChanhMuoi) which seems to violate the 2.1.3 rule that they "never combine with each other". Is there a mistake here?

This will make 

VTC (V T C lowcase or cap)
VertCoin (V C lowcase or cap)

As 2.1.4, and the same, 2.1.4 can combine with other but won't combine with each other.

With this (seem so complicated to me), will this tokens way too many combine? is it worth to try?

Thanks.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

You can contact us on https://keychainx.io or send mail to help@keychainx.io
