### ISSUE TITLE
Core Wallet - Error running run-all-pytests.py / btcrecover.py

### ISSUE THREAD

**Issue by marcovandenberg** [gurnec/btcrecover#161]
Hi all,

I get this when I run the scripts in the title:

Traceback (most recent call last):
  File "D:\Downloads\btcrecover-master\run-all-tests.py", line 79, in <module>
    print("Testing", full_version() + "\n")
  File "D:\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 52, in full_version
    calcsize("P") * 8,
TypeError: Struct() argument 1 must be string, not unicode

I followed the installation instructions meticulously as far as I am aware. Googling this error doesn't produce much, and unfortunately I don't know python myself.

I'd appreciate any guidance.

**Comment by marcovandenberg** [comment]
If it helps, I'm on Win10 64 bit.

**Comment by NoobAlert** [comment]
Same problem here - HELP!

**Comment by devlo** [comment]
Same here, 64 bit version of Python 2.7, on 32 bit version it works fine.

**Comment by JCreazy** [comment]
I have the same exact issue.  Both with 32 bit and 64 bit versions of Python.  Perhaps there is an error in the code.  I don't know much about coding and I certainly don't know enough about Python to fix it.  Maybe an expert can weight in.

**Comment by marcovandenberg** [comment]
I got this working eventually. Hopefully it can help some of you recover your wallets. The problem is that I misread one of the download pages. The page where we download the Python 2.7 release. Don't scroll down the page looking for the latest 2.7 release, the latest release is at the very top on the first page, it reads "Latest Python 2 Release - Python 2.7.14"

Once I did that and installed the right one, I could get the 32 bit and 64 bit versions running.

**Comment by gurnec** [comment]
Glad you figured it out, I'll update the install docs to be more clear.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
