### ISSUE TITLE
How to brute force passphrase

### ISSUE THREAD

**Issue by tom9000** [gurnec/btcrecover#164]
Hello,

Can anyone tell me how to set up the BTC Recover tokens.txt file so it will brute force a password / passphrase?

I mean trying all possible character combinations for a given number of characters for the password length.

Thank you

**Comment by rterwedo** [comment]
You mean upper, lower and specials for a pwd of X length?

**Comment by tom9000** [comment]
Yeah, sounds good !! ??

**Comment by rterwedo** [comment]
This needs more work to be efficient - but if you do not know your pwd, and its reasonably long, you probably will not find it.

+ ^1^%p
+ ^2^%p
....
+ ^n^%p   

where n = number of characters.  note this will do exactly that number of chars, not more or less.  Any ASCI letter, digit or symbol = %p

**Comment by rterwedo** [comment]
@tom9000 Please close. Its solved =)
