### ISSUE TITLE
Open reward for anyone help me build the best tokens file

### ISSUE THREAD

**Issue by Chococat** [gurnec/btcrecover#172]
Since gurnec seem busy and Vertcoin price keep going up, I have this open contract to anyone help me build the best tokens file.

**1. Reward**: Direct 100USD as ETH (at rate when you done tokens file), and if I find password I will transfer 500 VTC (or ETH, BTC.... at rate when password found).

**You can contact my skype: chococat044**

**2. Here info to build my token files:**
**2.1. Text:**
**2.1.1**
Vethed (V may lowcase or cap)

**2.1.2**
Western (W and T lowcase or cap)
WesternDigital (W T D lowcase or cap)
Western.Digital (W T D lowcase or cap)

**2.1.3**
ChanhMuoi (C and M may lowcase or cap)
Chanh.Muoi (C and M may lowcase or cap)
Chanh..Muoi ((C and M may lowcase or cap)
HaNoiComputer (H N C may lowcase or cap)
HaNoiComputer.com (H N C may lowcase or cap)
HaNoiComputer.vn (H N C may lowcase or cap)
TraChanh (T and C may lowcase or cap)
Tra.Chanh (T and C may lowcase or cap)
Tra..Chanh (T and C may lowcase or cap)
MinhKhai (M and K may lowcase or cap)

**2.1.4**
VTC (V T C lowcase or cap)
VertCoin (V C lowcase or cap)

_2.1.1_ may appear or not and if it appear, it combine with tokens in _2.1.2_, _2.1.3_, _2.1.4_ we may have password: Vethed.VTC.ChanhMuoi or WesternChanhMuoi, but we never have Vethed.Vethed

_2.1.2_ not may apprear or not, if token appear toekn only combine with 2.1.1,2.1.3, _2.1.4_, token never combine with eachother, we never have: WesternWesternDigital

_2.1.3_ not may apprear or not, if token appear toekn only combine with 2.1.1, 2.1.2, 2.1.4, token never combine with eachother, we never have: ChanhMuoiTraChanh

_2.1.4_ not may apprear or not, if token appear toekn only combine with 2.1.1, 2.1.2, 2.1.3, token never combine with eachother.

**2.2 Number:**
1012

2101
44099
444099
4492
1012
66099
627

1012 maybe appear or not, but if it appear, it combine with one of those, but all other are individual, they are not combine

For example: we may have 1012Vethed2101 or Vethed2101, but we wont have 4492Vethed44099

**2.3.**
Wallet

This maybe appear in password:

For example: we may have Vethed2101.Wallet or just Vethed2101

**2.4. Special Character maybe appear:**
!
.
*

@
?
%
%s (space)

all other special only appear once but . (dot) and (space) may appear 2 times max

For example: we may have Vethed ChanhMuoi@. or Vethed.ChanhMuoi.@ but we never have Vethed.ChanhMuoi@@

> Are there any tokens which definitely appear in your password?

So far I only know . (dot) definitely in password, and Wallet like 80% definitely appear in password.

> Can both of these appear in the same password guess: %i[v]ethed and %i[w]allet?

Yes, they may appear both in same password like: Vethed44099.Wallet or Vethed.ChanhMuoi.Wallet

> Can you tell me anything about the order in which the tokens should appear in your password? Is something always first, or is one token always before/after another token?

If wallet appear, it never stay first, it only stay after _2.1_, _2.2_.
! * % ? never stay in middle, if they apprear, they only stay first or last of password.
. (dot), %s (space), %% (%), @ they will stay random in password.

Thanks.

**Comment by rterwedo** [comment]
@Chococat I took a look at this, and have much time spent building token files.

You are most likely going to need more than 1...  (Some wallets I have seen need many).  We have tools to help build the token file if u need.

**Comment by Chococat** [comment]
@rterwedo hi, do you have skype, we can talk there for faster infomation? Thanks.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
