### ISSUE TITLE
keep getting TypeError: Struct() argument 1 must be string, not unicode.

### ISSUE THREAD

**Issue by soge-king** [gurnec/btcrecover#177]
im trying to get my pin back, keep getting this.
i dont know if its because i didnt download the scrypt (tried on command prompt but didnt work) or if my token files are being read like strings.

this is what i get:

C:\Users\F**********\Downloads\btcrecover-master>btcrecover.py  --utf8 --wallet bitcoin-wallet-backup-2017-12-07 --android-pin --tokenlist tokens.txt --threads 6 autosave save

Traceback (most recent call last):
  File "C:\Users\F**********\Downloads\btcrecover-master\btcrecover.py", line 35, in <module>
    print("Starting", btcrpass.full_version(),
  File "C:\Users\F**********\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 52, in full_version
    calcsize("P") * 8,
TypeError: Struct() argument 1 must be string, not unicode

**Comment by wtfloris** [comment]
For anyone coming here looking for a solution: you're probably using the wrong version of python2.7. It works for Python 2.7.14
