### ISSUE TITLE
Can't find scrypt library

### ISSUE THREAD

**Issue by errrrc** [gurnec/btcrecover#18]
Android btc spending pin. Getting the error of can't find scrypt library and that performance will be severely degraded. Followed the instructions to install scrypt and even uninstalled and reinstalled both 32 bit and 64 bit versions of everything. Can only try spending pins up to 5 digits because 6 digits will take >168 hours. trying 5 digits but I'm thinking it was probably 6 digits. It'll be 4 days before its done with 5 digits.

**Comment by errrrc** [comment]
still looking to find a way to try >5 digits

**Comment by gurnec** [comment]
Are you still having trouble with this? Which operating system are you on?

If you're on Windows, I just updated the [Windows scrypt installation docs](https://github.com/gurnec/btcrecover/blob/master/docs/INSTALL.md#windows-3) with the current versions of the required libraries. Try them out and let me know....

If you're on Linux, try installing more than one of the required libraries listed in [step 2 here](https://github.com/gurnec/btcrecover/blob/master/docs/INSTALL.md#linux-1). In theory, the pylibscrypt library should choose whichever it finds first (searching in fastest-to-slowest order).

**Comment by errrrc** [comment]
ok, now it works, however 6 digits returned no results so next time i go on vacation ill try 10 digits.. wondering if some malicious app changed the pin on my rooted phone?

**Comment by gurnec** [comment]
Seems unlikely... if a malicious app was in a position to change your PIN, it'd be in a position to steal your Bitcoin, so surely it would just do that, yes?

When I get a moment, I'll test a recent version of Bitcoin for Android to make sure nothing's changed that might break btcrecover. You could try running the the test-btcr.py script (just double-click it) to make sure there's nothing unusual about your Python install (skipped tests are OK, failed tests are not).

**Comment by errrrc** [comment]
made a dummy account and it cracked a 3 digit password in seconds.. guess i'll have to try longer strings although i feel like there's no way in hell i'd make a long password i couldn't remember.. when i try a 7 digit password it says out of memory after counting 89.4 million passwords.. the correct token would be %7d for a 7 digit password correct?

**Comment by gurnec** [comment]
That's correct. Add `-d` to the command line to avoid that error message.

Regards,
Chris


-------- Original Message --------

**Comment by errrrc** [comment]
k added -d worked like a charm a day and 8.8 million 8 digit combos later, awesome work! expect a tip!

**Comment by gurnec** [comment]
That's great, glad it worked!!

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
