### ISSUE TITLE
an entered address is invalid not a bitcoin P2PKH address

### ISSUE THREAD

**Issue by JWPapi** [gurnec/btcrecover#180]
Im getting this error message when putting in one of my public wallet adresses

**Comment by gurnec** [comment]
Are you trying to recover a slightly-wrong seed? A BIP-39 passphrase?

What wallet software are you using? If it has multiple types of wallets, which type of wallet did you create?

**Comment by JWPapi** [comment]
I think it was a segwit wallet thats why it didnt work, anyway I recovered it.

**Comment by jimgolian** [comment]
I am getting this same error.  Trying to recover a BIP-39 passphrase.  Using Trezor.

**Comment by satoshidoriannakamoto** [comment]
I am getting this same error. Trying to recover a BIP-39 passphrase. Using Trezor.
