### ISSUE TITLE
Help with tokens.txt elaboration

### ISSUE THREAD

**Issue by pedrohrcunha** [gurnec/btcrecover#183]
@gurnec , first of all, I would like to thank you for your amazingness. It's been a hell of a ride working my way through BTCrecover as a layman. That being said, would you mind helping me out with the writing of the following rules for my tokens.txt?

Password example:

QQQzzz222lllPPP)#

- One, two, three and four repetition variation
- Symbols at the end
- Caps and no caps to every character
- Three caps, three no caps, two caps, two no caps, etc. 

That's where I am stuck right now.

**Comment by rterwedo** [comment]
If it helps, break it apart into multiple token files.  Your description is unclear.

Is it always 5 sets of repetitions, that can be 1/2/3/4 repeating chars with 2 symbols on the end?  Is each set always just upper or lower and the next is the opposite?

If its always 5 sets, you could create 2^5 (32) token files alternating each iteration if you cannot easily figure it out in 1 token file.

**Comment by pedrohrcunha** [comment]
@rterwedo I didn't understand what you mean; breaking apart inside a tokens.txt? Like:
password
passwordvariation
passwordvariation2?

It is always 5 sets but alternating two-three-four of the same characters, like AA, AAA or AAAA. It's not probable that there are two symbols at the end, most probably one, but I want to test for both. One symbol, two symbol (every case of it). 

Yes I tend to alternate upper and lower -- OR -- lower and upper. I would like to test for both too. 

I don't know what you mean at the end, sorry, I'm learning.

**Comment by pedrohrcunha** [comment]
How do I see all the passwords testes with my tokens.txt file?

**Comment by rterwedo** [comment]
Use --listpass  and print to command line
