### ISSUE TITLE
tokens.txt desperate try

### ISSUE THREAD

**Issue by gorimagui** [gurnec/btcrecover#188]
Hi all,

I have an account in blockchain.info which I need to recover the access, This account is from 2013/14 and I don't have nor recall pw or 12 words. I am trying to get my pw with my backup aes.json file.

After trying all possibilities in my mind without success I am now desperate. I created a tokens.txt file with all letters in lower and uppercases, both of them, numbers from 0 to 9 and an @.

Am executing --tokenslist, --max-tokens 21 and --no-dupchecks. Could someone let me know if will test all possibilities from 1 letter or digit tol [21? My file is attached.

[tokens.txt](https://github.com/gurnec/btcrecover/files/1553273/tokens.txt)

Thanks for your help and code.

**Comment by pedrohrcunha** [comment]
If you don't have any idea of your password, btcrecover is not suitable. You should try Jack The Ripper.

**Comment by pedrohrcunha** [comment]
John The Ripper*

**Comment by rterwedo** [comment]
Yes, but you realize this will never complete in a reasonable time. ie millions of years...

**Comment by gorimagui** [comment]
Thank you for your replies. Am testing with JTR.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
