### ISSUE TITLE
False positive????

### ISSUE THREAD

**Issue by sigmabena20** [gurnec/btcrecover#19]
I wonder if it is possible that the program returns a "false positive". The issue is that after a difficult period of brute force, the program has given me a password that always gives me as "password found", but when I try to unlock the account, "bitwallet" keeps telling me that the password is incorrect.

Likewise report that the alleged password does not contain unrecognized characters and is shaped through a crucible and convinations own passwords (using a token.txt).

**Comment by sigmabena20** [comment]
Sorry, where I wrote "bitwallet", I want say "multibit"

**Comment by gurnec** [comment]
False positives definitely can happen, however they should be *extremely* rare, depending on the wallet type.

Which version of MultiBit are you using? Is it MultiBit Classic or MultiBit HD? If it's classic, are you running btcrecover with a .key file or with a .wallet.aes file?

**Comment by sigmabena20** [comment]
OK, it's curious..

My MultiBIt is the Classic whita .key file. And the password it's a very strong headache.. ;(

**Comment by gurnec** [comment]
Have you tried decrypting the .key file with openssl? The openssl command to do this is in the [MultiBit wiki here](https://github.com/keepkey/multibit/wiki/Export%20and%20limited%20import%20of%20private%20keys#development-notes). If you're on Windows (other OS's include openssl by default), you can download [openssl here](https://slproweb.com/products/Win32OpenSSL.html) (choose the "Light" version at the top of the downloads table).

Do you recall about how many passwords btcrecover said there were to try in total?

**Comment by jamescoxon** [comment]
Just had the same thing, searching for a multbit classic password using the .key file - a false positive after about 48hrs of searching! Checked the password using the openssl command and using the actual wallet and no joy.

Nevermind - restarted the search excluding that combination - hopefully will find something soon...

**Comment by prophecynine** [comment]
does the false positive imply any connection with the real passphrase?

**Comment by prophecynine** [comment]
So far I've had 2 false positives. one was after 15863751641 attempts, the second was after 167667359104 attempts (with an alternate tokens.txt file) The openssl trick is a nice way to doublecheck, but it's been a bit of a rollercoaster...

**Comment by rterwedo** [comment]
What setup are you using to get 167 billion combos in 48 hours?

**Comment by prophecynine** [comment]
My studio computer has 16gb ram and an i7 2700k :) running in ubuntu 64 bit

**Comment by rterwedo** [comment]
I am running on a 32 CPU, 4 GPU, 60gb, ubuntu 64 bit setup.  I performance tested and in 48 hours, I could only do 363 million combos.

What command line settings are you using?

**Comment by opies32765** [comment]
does anyone know if btcrecover will support multiple GPU's in SLI ?

Thanks in advance

**Comment by gurnec** [comment]
FYI the MultiBit false positive rate has (finally) been drastically reduced in 8a6e74e, see also #72.
