### ISSUE TITLE
Run-All-test seems to have failed

### ISSUE THREAD

**Issue by azjnson** [gurnec/btcrecover#191]
This is what I get when I run the Run-All-Tests.
![test_all](https://user-images.githubusercontent.com/34514165/33944788-f9f11c12-dfd1-11e7-8598-5564052e165d.jpg)

Can you help Diagnose what the issue is.
Thank you,

**Comment by rterwedo** [comment]
Do u have an android pin wallet? - Thats what seems to have errored

**Comment by azjnson** [comment]
no I am using a wallet.aes.json file.
So this should work correctly?

**Comment by rterwedo** [comment]
Yes, most likely

**Comment by azjnson** [comment]
Thank you...
I noticed that there are 3 .json test wallets.
Do we have a token.txt that we could run against them to see if the program is working?

**Comment by rterwedo** [comment]
You can create a new wallet with a known pwd and test that.

**Comment by gurnec** [comment]
Even though this test failure won't affect your wallet type, thanks for reporting it. It appears to be a minor issue in pylibscript, and I've submitted a patch request upstream at jvarho/pylibscrypt#37.

In the mean time, this particular test failure can be ignored. Thanks!

**Comment by gurnec** [comment]
The issue has been fixed in pylibscrypt, and the tests should succeed after upgrading it to the most recent version:

    pip install --upgrade pylibscrypt

Your other issue remains open regarding your problems with Blockchain.info wallets.
