### ISSUE TITLE
Strange error on GPU acceleration

### ISSUE THREAD

**Issue by Riteraa** [gurnec/btcrecover#201]
I'm trying to run GPU acceleration but I'm having a strange error:

C:\Python27\python.exe btcrecover.py --wallet wallet.dat --no-dup --utf8 --tokenlist token3dig.txt --enable-gpu --gpu-names 1 --global-ws 4096 --local-ws 512
Starting btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Wallet difficulty: 116,687 SHA-512 iterations
Traceback (most recent call last):
File "btcrecover.py", line 38, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\buraj\Desktop\btcrecover-master\btcrecover\btcrpass.py", line 5488, in main
    print("Using OpenCL", pyopencl.device_type.to_string(cl_devices[0].type), cl_devices[0].name.strip())
  File "C:\Python27\lib\site-packages\pyopencl\cffi_cl.py", line 346, in to_string
    % (value, cls.__name__))
ValueError: a name for value 4 was not found in device_type

The `--list-gpus` command lists: 

Starting btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
#1 GeForce GTX 1050 Ti
#2 Intel(R) HD Graphics 630
#3 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

When I run the `C:\python27\python -m btcrecover.test.test_passwords -v --utf8 GPUTests` test, I get 2 successfull tests:

test_bitcoincore_cl (__main__.Test08KeyDecryption) ... ok 
test_bitcoincore_cl_unicode (__main__.Test08KeyDecryption) ... ok
test_bitcoincore_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'windows kills and restarts drivers which take too long'
test_bitcoincore_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'
test_armory_cl (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_mem_factor (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_no_interrupts (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
test_armory_cl_sli (__main__.Test08KeyDecryption) ... skipped 'requires Armory and ASCII mode'
Ran 8 tests in 15.494s
OK (skipped=6)

My pc has Windows 10 x64 and the latest NVIDIA driver (388.59). Other OpenCL programs run perfectly.

Any ideas on what's happening?

**Comment by rterwedo** [comment]
Did you try without having this flag?  --gpu-names 1   

The error looks like its trying to use gpy #4 which doesn't exist.

**Comment by Riteraa** [comment]
Yes, I tried, same error.

**Comment by rterwedo** [comment]
Try changing it around, ie 1  then 2, etc

Try no other flags exept wallet and token (this will use cpu and not gpus). If you get it here, try an new install.

I think you have something being sent from command line (previous command maybe?) that keeps being used.

**Comment by FireWalkerX** [comment]
i get the exact same error

**Comment by rterwedo** [comment]
@gurnec Check this out... - weird error + solution..

**Comment by RonJon715** [comment]
I get the exact same error when trying to use GPU acceleration:

C:\Users\RonJon\Downloads\btcrecover-master>C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --enable-gpu --gpu-names 1 --max-tokens 4
Starting btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Wallet difficulty: 87,126 SHA-512 iterations
Traceback (most recent call last):
  File "btcrecover.py", line 38, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\RonJon\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 5488, in main
    print("Using OpenCL", pyopencl.device_type.to_string(cl_devices[0].type), cl_devices[0].name.strip())
  File "C:\python27\lib\site-packages\pyopencl\cffi_cl.py", line 346, in to_string
    % (value, cls.__name__))
ValueError: a name for value 4 was not found in device_type

**Comment by pedrohrcunha** [comment]
Afaik, @Riteraa solved his issue. I know him. Will probably post his solution here.

**Comment by RonJon715** [comment]
I'd really appreciate if you could post the solution.  It's been driving me crazy.

**Comment by rterwedo** [comment]
@RonJon715 its posted above, read what @FireWalkerX wrote.  Its not a prob with us, its a library

**Comment by RonJon715** [comment]
Ok, I just didn't understand the fix.  Do I need to update that specific Python library?

**Comment by FireWalkerX** [comment]
locate this file:
(windows)
C:\python27\lib\site-packages\pyopencl\cffi_cl.py

find this:
class device_type(ConstantsNamespace): # noqa
@classmethod
def to_string(cls, value, default_format=None):
for name in dir(cls):
if name in ("DEFAULT", "ALL"):
continue
if not name.startswith(""):
bitfield = getattr(cls, name)
if isinstance(bitfield, int) and ((bitfield & value) == bitfield):
return name
# comment out his
    #if default_format is None:
    #    raise ValueError("a name for value %d was not found in %s"
    #                     % (value, cls.__name__))
    #else:
    #    return default_format % value

**Comment by RonJon715** [comment]
I see this but the only difference I have is here: 

if not name.startswith("_"):

So, remove the underscore?

**Comment by FireWalkerX** [comment]
no, below it is this:
if default_format is None:
    raise ValueError("a name for value %d was not found in %s"
                     % (value, cls.__name__))
else:
    return default_format % value

change to
#if default_format is None:
#    raise ValueError("a name for value %d was not found in %s"
#                     % (value, cls.__name__))
#else:
#    return default_format % value

**Comment by RonJon715** [comment]
That looks exactly like what I have:

class device_type(_ConstantsNamespace):  # noqa
    @classmethod
    def to_string(cls, value, default_format=None):
        for name in dir(cls):
            if name in ("DEFAULT", "ALL"):
                continue
            if not name.startswith("_"):
                bitfield = getattr(cls, name)
                if isinstance(bitfield, int) and ((bitfield & value) == bitfield):
                    return name

        if default_format is None:
            raise ValueError("a name for value %d was not found in %s"
                             % (value, cls.name))
        else:
            return default_format % value

I'm really confused.  I tried running it with the small changes and got another error:
C:\Users\RonJon Faulkner\Downloads\btcrecover-master>C:\python27\python btcrecover.py --wallet wallet.dat --tokenlist tokens.txt --enable-gpu --gpu-names 1 --max-tokens 4
Starting btcrecover 0.17.9 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
Wallet difficulty: 87,126 SHA-512 iterations
Traceback (most recent call last):
  File "btcrecover.py", line 38, in <module>
    (password_found, not_found_msg) = btcrpass.main()
  File "C:\Users\RonJon Faulkner\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 5488, in main
    print("Using OpenCL", pyopencl.device_type.to_string(cl_devices[0].type), cl_devices[0].name.strip())
  File "C:\python27\lib\site-packages\pyopencl\cffi_cl.py", line 346, in to_string
    % (value, cls.name))
AttributeError: type object 'device_type' has no attribute 'name'

**Comment by FireWalkerX** [comment]
every line you have in the square box, put a # in front of it

**Comment by RonJon715** [comment]
Thanks.  That was simple. I thought you were doing that for formatting.  Working now.

**Comment by rterwedo** [comment]
@Riteraa  can you close? Its solved!

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
