### ISSUE TITLE
Crash at 89.4M passwords

### ISSUE THREAD

**Issue by danmermels** [gurnec/btcrecover#204]
btcrecover always crashes at either counting or running passwords when reaching the count of 89.466.629.....

Any idea why ? 

Thanks

D.

**Comment by rterwedo** [comment]
Ram? Can you try --no-eta --no-dupchecks  ?  or pipe in via pypy?

**Comment by rterwedo** [comment]
@danmermels can you close please?  Its solved =)

**Comment by rterwedo** [comment]
@danmermels please close issue...

**Comment by danmermels** [comment]
Thank you. Sorry for leaving it open for so long. didnt realize.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
