### ISSUE TITLE
trying to recover seed using a ledger ethereum address

### ISSUE THREAD

**Issue by zarinmedia** [gurnec/btcrecover#224]
I have a passphrase written down from a ledger nano S, and an ethereum address on that wallet that ether was sent to. The passphrase seems to not be correct and I am trying to recover it.

When I run seedrecover.py and it gives me the dialog "Please select your wallet type"

I tried choosing "standard BIP39/BIP44" since the ethereum standard says "NOT ledger" but it doesn't seem to work with an ethereum address.

I tried running the "Ethereum Standard BIP39/BIP44", it goes through the motions, but is not able to figure the passphrase.

Is there something I am missing to get the selection for the ledger wallet to work with an Ethereum address?

![image](https://user-images.githubusercontent.com/5041345/34632965-dfe326e4-f246-11e7-9f7b-6998237c9cc5.png)

![capture4](https://user-images.githubusercontent.com/5041345/34632971-ee680dc4-f246-11e7-9ddc-d0dd0d9136ae.JPG)

**Comment by zarinmedia** [comment]
since then, some gracious soul has pointed me to this post: https://github.com/gurnec/btcrecover/issues/141

Anyone tested this out and know exactly what command line parameters to use in this case?

**Comment by zarinmedia** [comment]
I just wanted to follow this up with a resolution to my problem. Thanks to my new hero Travis (grnqrtr) who pointed me in the right direction (post #141) and gurnec who originally wrote the post!

In a case where you only have an ethereum wallet address for a ledger nano S, you cant run the interface, you've got to run it in the command line like this:

> ./seedrecover.py --wallet-type ethereum --bip32-path "m/44'/60'/0'/" --addr-limit 1

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
