### ISSUE TITLE
Use Token Multipule Times

### ISSUE THREAD

**Issue by PixelBully** [gurnec/btcrecover#234]
Hi All,

First of all, great script. I'm sure i'll be able to eventually crack my way into my wallet.

Second, is there a way to configure it to use a token multiple times in password attempt?

For example, tokens file:
foo
bar

Possible password attempts:
foobarfoo
....

Thanks!

**Comment by rterwedo** [comment]
Have it on multiple lines.
```

 foo bar
foo bar
foo bar
```

Go ahead and close this out for Chris.

**Comment by PixelBully** [comment]
Of course! 
Thanks guys.
