### ISSUE TITLE
More brute force orientated token file if possible to create

### ISSUE THREAD

**Issue by ghost** [gurnec/btcrecover#235]
It would be good if btcrecover was able to function easily as a brute force password decrypter in addition to the things it already does.

At the moment the best option is to enter a sting of %P's or %p's of a given length and run the code.  But most people trying to brute force a password are aware of how long this would take so a few new options in how the token file is created could help greatly in reducing the amount of time this method would take. 

I think number 2. may solve the problem for me but some people may find it helpful if 1. was also added as an option. 

1. Being able to exclude characters.  This can hopefully relatively easily be implemented by giving an option to enter a list of characters in the token file that don't need to appear anywhere in the password combination tests. 

2. No repetitions.  If an ? appears in a password test - telling the code to not test for another ? anywhere else in the password. 

and an extension of this (which is maybe only specifically useful for me as I know I had no repetitions of the same letter in any form - but hopefully other people also could benefit from): 

   2b. No repetitions of a lower case letter if the upper case form has already appeared and vice a versa. 
         e.g. 'A' should not appear anywhere in the remaining characters if 'a' has already appeared in the 
         password

You could then use %[chars] multiple times and replace chars with all the possible characters that were in your password (i.e. all possible characters in your password go between the brackets).  

So for a password of length 6 the whole token file would look something like:
------------------------------------------------------------------------
%[chars]%[chars]%[chars]%[chars]%[chars]%[chars]

no_repetiton <- yes

no_repetiton_lower_or_upper <- no 

-----------------------------------------------------------------------
(in my case I could set no_repetiton_lower_or_upper to yes)
 
If anyone has any idea how these changes could be implemented then it would be very useful, not sure if the programs original creator would need to implement these changes themselves or if there is an option for someone else to add these changes but any advice either way would be much appreciated.

**Comment by rterwedo** [comment]
You can do a bunch of this already...  additionally there are custom token generator options.

If you wanted a 6 char excluding letters in  g e c k o

```
+ ^1^a ....   ^1^z    (dont have g e c k o in there)
+ ^2^a....  
+
+
+
+
```

Additionally you can feed passwords in from other sources... like JTR or hashcat etc.

**Comment by pedrohrcunha** [comment]
@rterwedo I didn't understand your code. Could you clarify it to me? It would be useful. What's that space ....?

**Comment by rterwedo** [comment]
@pedrohrcunha its on the token generator page in the documentation.

Use combos of + and ^1^ relative anchors, if u dont know exact length, dont use relative anchors.

**Comment by ghost** [comment]
@rterwedo.  Thank you very much for the answer this will work for excluding letters. 

Do you have any idea how to prevent repeats anywhere in the password - or is this something that would have to be done through something like jtr?  There are a few solutions to issues on here that tell you how to prevent adjacent character repeats but these do not work for avoiding repeats anywhere else in the password.

**Comment by rterwedo** [comment]
@big-green-gecko 

You can craft token files (probably need more than 1) to do this or use another program (JTR, HC, etc).  Depending on keyspace size when we attack a keyspace, and want to exclude stuff like this we make ~5-20.000 token files for a wallet.

Please close as this is not an issue, its support related.  =)

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
