### ISSUE TITLE
Can GPU Acceleration be used on Electrum Wallets 

### ISSUE THREAD

**Issue by ghost** [gurnec/btcrecover#236]
It's not mentioned anywhere in the GPU Acceleration Guides.  Maybe a reason for this is that they have systems designed to resist GPU-based acceleration like Armory wallets but that are even stronger so not even worth mentioning in the guide?

**Comment by rterwedo** [comment]
Try it and see if it works...  =)  I don't have an electrum wallet or I would try.

Please close as this is not an issue, its support related.

**Comment by rterwedo** [comment]
@big-green-gecko Please close

**Comment by ghost** [comment]
@rterwedo Where do you post support related questions?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover
