### ISSUE TITLE
Any reason not to use --listpass > passwords.txt, followed by --passwordlist passwords.txt?

### ISSUE THREAD

**Issue by winnph** [gurnec/btcrecover#237]
Is there any performance-related reason for using a list generated on the fly from a token file instead of creating a password list using the --listpass option, and then loading that list with --passwordlist later? For example:

`./btcrecover.py --tokenlist tokens.txt --typos-map typos.txt --listpass > passwords.txt`

Followed by:

`./btcrecover.py --wallet wallet.dat --passwordlist passwords.txt`

I like the idea of generating the list so I can look at it and make sure I didn't make any silly syntax mistakes in the token file, and also it seems like if I try broader and broader strategies one after another, then it would be easier this way to remove duplicates using `grep` to compare a list of all previously tried passwords to each newly generated list (presumably this would be somewhat time consuming but faster than trying them over again). Or is there a better way to do that with btcrecover that I'm missing from the tutorial?

**Comment by rterwedo** [comment]
Have you tried it?  Experiment... Read the docs, other issues...

It depends on your keyspace.  If you have fast IO using a pregen list is faster.  However if your keyspace is huge good luck pregen a list of 10s or 100s of billions.

Go ahead and close this out so its not open for Chris. =)

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
