### ISSUE TITLE
Uses only 1 CPU core to generate password list

### ISSUE THREAD

**Issue by winnph** [gurnec/btcrecover#238]
I am using btcrecover to generate a fairly large password list, and since that can be time consuming, I opened the system monitor to see if all four CPU cores were being maxed out. One core is at 100% while the other three are barely being used (0-2%).

Is this a known limitation of btcrecover or is there some flag that can be enabled to have it use all available CPU cores during the password generation phase? This is an Intel Core i5 6400K, if that makes a difference.

**Comment by rterwedo** [comment]
Its not a multi threaded setup.  So not an issue.  

Go ahead and close this for Chris.

**Comment by winnph** [comment]
So to answer the question, this is a known limitation and there is no way to force it to use all cores?

**Comment by winnph** [comment]
So to answer the question, this is a known limitation and there is no way to force it to use all cores?

**Comment by rterwedo** [comment]
Yes this is known limitation of the currently architected setup.

**Comment by winnph** [comment]
It's a shame that only password **guessing** supports multi-threading, not password **generating**, since that means for GPU-bound wallets with complex token files, it'll probably take longer to generate the list than to guess the list. I gather that multi-threading is not as easy as it should be in Python, but this is something I don't really understand sufficiently to say much more than that.

I'll close it out -- thanks for the feedback.

**Comment by rterwedo** [comment]
Use pypy (its in an issue and documented already) to feed into for faster generating.  I wont retype it, but thats the fastest way to gen via btcr.
