### ISSUE TITLE
blockchain v0.0 test wallet password

### ISSUE THREAD

**Issue by indicava** [gurnec/btcrecover#24]
Could you please provide the password for the file found in:

btcrecover-master/test-wallets/blockchain-v0.0-wallet.aes.json

So I can test if my setup is working against my own Blockchain V0 wallet?

**Comment by gurnec** [comment]
Sure, all of the test wallets have a password of `btcr-test-password`.

**Comment by indicava** [comment]
Thank you very much! 
I am actually using btcrecover just for password generation and am trying to pipe it to john/hashcat for GPU performance. 
btcrecover obviously cracks the password, for some reason john/hashcat fail to do so. 
I will keep at it, thanks again for replying!

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
