### ISSUE TITLE
How to get started??

### ISSUE THREAD

**Issue by opensourcesawmill** [gurnec/btcrecover#240]
I had a friend who made a typo in his 24 word seed - I used this to recover it..

I've been programming for a long time, but I still mainly use a form of assembly language.

I'd like to study this code - it's very fascinating - does anyone have a quick start guide on what to install and which environment to use to look at the code??

Much thanks..

**Comment by rterwedo** [comment]
Its in the links on the homepage, prob one of best documented OS projects I have seen...

**Comment by rterwedo** [comment]
@opensourcesawmill - go ahead and close this out as its not an issue for Chris.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
