### ISSUE TITLE
Regarding wildcard confusion between %[chars] & %[0-9a-f]

### ISSUE THREAD

**Issue by mkvtvseries** [gurnec/btcrecover#245]
%[0-9a-f] - exactly 1 of these characters: 0123456789abcdef
%[chars] - exactly 1 of the characters between [ and ] (e.g. either a c, h, a, r, or s)

%[chars] - Does third bracket [ ]is included between characters given ??

If %[abcdefiklmno] then does it mean 
exactly 1 of these characters: abcdefiklmno
OR  either a,b,c,d,e,f,i,k,l,m,n or o

**Comment by crypto-recovery** [comment]
Apologies, I'm not sure that I entirely understand your question.  Here are a some examples of when you might use the two approaches:

> %[0-9a-f]
You know that your password starts with the string "Secret", followed by one character in the list [0123456789abcdef].  So, you specify the following in tokens.txt:

+ ^Secret
+ %[0-9a-f]$

btcrecover.py will test each of the following password variations:
Secret0
Secret1
...
Secretf

> %[chars]
You know that your password starts with the string "Secret", followed by one character in the list [randm]. So, you specify the following in tokens.txt:

+ ^Secret
+ %[randm]$

btcrecover.py will test each of the following password variations:
Secretr
Secreta
...
Secretm

Does that answer your question, or did I misunderstand it?

Thanks,
Chris

**Comment by mkvtvseries** [comment]
thank crypto-recovery
