### ISSUE TITLE
Mutual Exclusion not working for my case

### ISSUE THREAD

**Issue by CarlWillhelm** [gurnec/btcrecover#247]
Hey there so I want to do the following (just the basic example of my problem):
Pw consists of 2 words ("Bird" at first position, "Tomatooo" at last position) and possibly a "space" or "$" or **nothing** in between. 
So there are these options I want to test:

- BirdTomatooo
- Bird Tomatooo
- Bird$Tomatooo

My token file looks like this:
```
+ ^1^Bird
^2^%s %S
+ ^3^Tomatooo
```

But the problem is that by testing this with --listpass I only get 2 possible combinations:
- Bird Tomatooo
- Bird$Tomatooo

Am I doing something wrong? If so how would you write this correctly?
Thanks for any help.

**Comment by pedrohrcunha** [comment]
Try using ^ ^,^ $ instead of ^1^ ^2^ and ^3^.

**Comment by CarlWillhelm** [comment]
not sure how this helps me since the order is important. Bird needs to be checked only at first postion and Tomatooo only after Bird (which can be followed by a space or a $ or nothing). This is just a simplification for a more complex problem im trying to solve with more then 2 words for which the order is known but its not sure if a space or a $ is in btween the words.
I think I solved it like this now:
```
+ ^1^Bird ^1^Bird%s ^1^Bird%S
+ ^2^Tomatooo
```

which can be used for more words where the order is already known like this for example:
```
+ ^1^Bird ^1^Bird%s ^1^Bird%S
+ ^2^Tomatooo ^2^Tomatooo%s ^2^Tomatooo%S
+ ^3^anotherword ^3^anotherword%s ^3^anotherword%S
+ .... and so on
```
