### ISSUE TITLE
Password being found but it's not correct?

### ISSUE THREAD

**Issue by kost123** [gurnec/btcrecover#25]
So I tried to use btcrecover on a strongcoin key I have(same as bitcoin android/multibit.. I tried it before against a known password on a key), I ran it and it said password found, tried a few more times, found everytime, but then I try to decrypt with openssl and using the strongcoin website and using multibit.. all throw a password incorrect, So I tried to output the contents of "b58_privkey" variable after this line:

b58_privkey = l_aes256_cbc_decrypt(key1 + key2, iv, encrypted_block)

 and it's just a lot of rubbish that makes my CMD window crash.

here is what I get from openssl:

KpVuZ1ryWPTsQ6g2mI[n▬<¾·_Ï¶┌îØNXçLµp╦<&Ë▬┤╗ZÙò}¼bad decrypt

Is that why.. it starts with K

edit: so I figure it's because there is a 1/300billion chance of finding an incorrect password that when running long char bruteforce that it messes up :/ Any additional checks can be done to make sure its correct?

**Comment by gurnec** [comment]
btcrecover is not intended as a general-purpose brute-forcer. When used as such, it *will* find false positives, especially with MultiBit .key files. This is not considered a bug, it is simply a case of using a piece of software for a purpose outside of its design specs. Closing as wontfix.

If you need to contact me further regarding this, you can [PM me as user "gurnec" on Reddit](https://www.reddit.com/message/compose/?to=gurnec).
