### ISSUE TITLE
"NotImplementedError: Unsupported Electrum2 seed version 16"

### ISSUE THREAD

**Issue by DavidVeksler** [gurnec/btcrecover#250]
> Traceback (most recent call last):
>   File "extract-electrum2-partmpk.py", line 69, in <module>
>     raise NotImplementedError("Unsupported Electrum2 seed version " + str(seed_version))

Is there any way that I can convert my wallet file to a supported format for processing?

**Comment by extricate-me** [comment]
I'm also dealing with this. There seems to be some confusion around what type of wallet I have. This is a wallet that was created in 2015. The parts that seem relevant are

```
{
    "seed_version": 16,
    "keystore": {
        "mpk":  "<LONGSTRING>",
        "seed": "<LONGSTRING>",
        "type": "old"
    }
}
```

I've tried changing `seed_version` to 4 but to no effect.

**Comment by dginovker** [comment]
Having this issue as well. Has anyone fixed it?

**Comment by DavidVeksler** [comment]
You can comment out the version check if just want to disable it:
btcrpass.py:
```
#        if wallet.get("seed_version") not in (11, 12, 13) and wallet_type != "imported":  # all 2.x versions as of Oct 2016
#            raise NotImplementedError("Unsupported Electrum2 seed version " + unicode(seed_version))
```
