### ISSUE TITLE
Indefinite password counting

### ISSUE THREAD

**Issue by gkrizek** [gurnec/btcrecover#251]
I have being running btcrecover for about 1 month now and it's still at the "Counting Passwords..." stage. It's currently at 350 Billion passwords. Is my token list too complex or is btcrecover just running wild now?

Is there any way to check the progress? Did I do something wrong?

My command: `./btcrecover.py --wallet key-backup.key --token token.txt --no-dupchecks`

Contents of my `token.txt` file, (edited of course):

```
+ ^Word1
^,^Word2 ^,^word2
^,^Word3 ^,^word3
^,^Word4 ^,^word4
^,^Word5 ^,^word5
^,^Word6 ^,^word6
^,^Word7 ^,^word7
^,^Word8 ^,^word8
Word9 word9
Word10 word10
Word11 word11
1
123
!$
```

**Comment by pedrohrcunha** [comment]
Just use --no-eta. Didn't you know this command?

**Comment by gkrizek** [comment]
Nope! I didn’t. Now I feel foolish, haha. I obviously didn’t read the docs well enough before using. Thank you!
