### ISSUE TITLE
Help regarding ~!@#$% etc which wildcard does it belong to?

### ISSUE THREAD

**Issue by mkvtvseries** [gurnec/btcrecover#255]
Special characters like ~!@#$% , which wildcard does it belong to ?

**Comment by 505Mike** [comment]
%P

**Comment by winnph** [comment]
obviously you can also just do %[~!@#$%] if you want to limit it just to a certain set of special characters instead of the full character set.

**Comment by mkvtvseries** [comment]
Thank

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
