### ISSUE TITLE
Argument --tokenlist

### ISSUE THREAD

**Issue by crylent** [gurnec/btcrecover#262]
I write in command line:
C:\Program Files (x86)\btcrecover-master>btcrecover.py --wallet wallet.dat --tokenlist tokens.txt

Response:
Starting btcrecover 0.17.10 on Python 2.7.14 64-bit, 16-bit unicodes, 32-bit ints
btcrecover.py: error: argument --tokenlist or --passwordlist is required (or file btcrecover-tokens-auto.txt must be present)

Why do I get this error? File tokens.txt exists in the directory C:\Program Files (x86)\btcrecover-master

**Comment by crypto-recovery** [comment]
Good morning,

If you cd to C:\Program Files (x86)\btcrecover-master, what is the output from running the "dir" command?

Thanks,
Chris

**Comment by crylent** [comment]
```
25.02.2018  18:42    <DIR>          .
25.02.2018  18:42    <DIR>          ..
19.02.2018  15:49                26 .gitignore
19.02.2018  15:49               947 .travis.install-dependencies.sh
19.02.2018  15:49               141 .travis.yml
19.02.2018  15:49    <DIR>          aespython
19.02.2018  15:49    <DIR>          btcrecover
19.02.2018  15:49             2 123 btcrecover.py
19.02.2018  15:49               259 btcrecoveru.py
19.02.2018  15:49             3 211 create-address-db.py
19.02.2018  15:49    <DIR>          docs
19.02.2018  15:49    <DIR>          extract-scripts
19.02.2018  15:49            15 220 LICENSE.txt
19.02.2018  15:49    <DIR>          passlib
19.02.2018  15:49    <DIR>          progressbar
19.02.2018  15:49             5 243 README.md
19.02.2018  15:49             5 917 run-all-tests.py
19.02.2018  15:49             2 356 seedrecover.py
23.02.2018  17:17               231 tokens.txt
19.02.2018  15:49            48 505 TUTORIAL.md
19.02.2018  15:49    <DIR>          typos
20.02.2018  19:03         1 007 616 wallet.dat
```

**Comment by crypto-recovery** [comment]
That looks right to me.  

It also looks like python is executing the btcrecover.py script, so I assume that you have identified the location of the python binary in btcrecover.py?

What if you were to fully specify the path to everything?  (My example assumes that your python binary is located in C:\python27\python -- you should substitute the actual location on your computer).

Ex: 

C:\python27\python C:\Program Files (x86)\btcrecover-master\btcrecover.py --wallet C:\Program Files (x86)\btcrecover-master\wallet.dat --tokenlist C:\Program Files (x86)\btcrecover-master\tokens.txt

Thanks,
Chris

**Comment by crylent** [comment]
"It helped me
Thanks

**Comment by crylent** [comment]
C:\python27\python "C:\Program Files (x86)\btcrecover-master\btcrecover.py" --wallet "C:\Program Files (x86)\btcrecover-master\wallet.dat" --tokenlist "C:\Program Files (x86)\btcrecover-master\tokens.txt"
- it helped me
Thanks

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
