### ISSUE TITLE
No repeated tokens allowed in BTCRecover

### ISSUE THREAD

**Issue by gregorycarnegie** [gurnec/btcrecover#270]
If I have 4 tokens and I know that three of the tokens could appear in only the first, second and last parts of my password. E.g.:

+ ^cat ^dog ^bird
+ ^2^cat ^2^dog ^2^bird
+ ^3^moose
+ cat$ dog$ bird$

I want each token to be used only once. How can I instruct BTCRecover to exclude passwords that use repeated tokens such as "**cat**cat**moose**cat", but only include passwords such as "**cat**dog**moose**bird" or "**bird**dog**moose**cat" where there are no repeated tokens?

**Comment by wertzuiop123** [comment]
same question. how do you define a "OR" on a specific place?
^1^ilikemy
^2^cat ^2^dog ^2^bird
^3^and
^4^ilikemy
^5^cat ^5^dog ^5^bird
^6^and
^7^ilikemy
^8^cat ^8^dog ^8^bird

cat, dog, bird should only tried once in a try

**Comment by crypto-recovery** [comment]
> How can I instruct BTCRecover to exclude passwords that use repeated tokens such as "catcatmoosecat"

What if you wrote this as:
^cat ^2^cat cat$
^dog ^2^dog dog$
^bird ^2^bird bird$
^3^moose

This tells btcrecover.py to only use "cat" in the first, second or last position, "dog" in the first, second or last position, "bird" in the first, second or last position, and "moose" in only the 3rd position.  You won't end up with "catcatmoosecat" because by specifying all the "cat" options on the same line you tell btcrecover.py to use "cat" either zero or one times.

You may also want to play around with using the "+" symbol at the beginning of the line to require certain words in the password variations.  For example: 

\+ ^cat ^2^cat cat$

would mean that "cat" is a required string and that it should appear in either the first, second or last position.

>same question. how do you define a "OR" on a specific place?
^1^ilikemy
^4^ilikemy
^7^ilikemy

Do you mean: how do you direct btcrecover.py to try password variations with "ilikemy" in the first, fourth or seventh position, but only use the expression "ilikemy" either zero or one times?

Try this:
^1^ilikemy ^4^ilikemy ^7^ilikemy

This configuration would mean that "ilikemy" is a required string:
\+ ^1^ilikemy ^4^ilikemy ^7^ilikemy

Does that address your question?

Thanks,
Chris

**Comment by gregorycarnegie** [comment]
@crypto-recovery , your method works very well. I am achieving success with small lists of tokens; but not so much with more extensive lists. The current project I'm working on uses 24 tokens, and each token has either 1, 2, 3 or 5 possible positions rather than the full 24. Below you will see my token list, but as it is, its generating zero passwords; could it be that I have used too many tokens for btcrecover to use?:

###################################################3! [1st, 8th and 12th]
^cat ^8^cat ^12^cat
^now ^8^now ^12^now
^goo ^8^goo ^12^goo
###################################################3! [2nd, 9th and 24th]
^2^eon ^9^eon eon$
^2^god ^9^god god$
^2^coat ^9^coat coat$
###################################################2! [4th and 14th]
^4^ant ^14^ant
^4^dig ^14^dig
###################################################2! [5th and 6th]
^5^bun ^5^bun
^5^cot ^6^cot
###################################################3! [3rd, 17th and 22nd]
^3^tree ^17^tree ^22^tree
^3^shoe ^17^shoe ^22^shoe
^3^light ^17^light ^22^light
###################################################1! [7th]
^7^hat
###################################################1! [19th]
^19^rich
###################################################3! [15th, 16th and 20th]
^15^repo ^16^repo ^20^repo
^15^dot ^16^dot ^20^dot
^15^show ^16^show ^20^show
###################################################5! [10th, 11th, 13th, 21st and 23rd]
^10^woe ^11^woe ^13^woe ^21^woe ^23^woe
^10^equal ^11^equal ^13^equal ^21^equal ^23^equal
^10^over ^11^over ^13^over ^21^over ^23^over
^10^can ^11^can ^13^can ^21^can ^23^can
^10^van ^11^van ^13^van ^21^van ^23^van
###################################################1! [18th]
^18^gut

PS
+ min-tokens has been set to 24. 
+ I have also tried making each line required; no results there either.
+ The numbers at the end of the comment lines were to help me do some calculations. They can be ignored.

**Comment by gregorycarnegie** [comment]
I have discovered that there is nothing wrong with what I have written (@crypto-recovery's method works for larger numbers after all). There seems to be a non-linear increase (probably exponential) in the amount of time it takes btcrecover to read a token list for each anchor that you add.

**Comment by davidhekim** [comment]
So many people trying to solve Montecrypto, lol

**Comment by gregorycarnegie** [comment]
@Dupstre so you figured me out lol.

**Comment by pedrohrcunha** [comment]
@gregorycarnegie Do you know the command --no-eta?

**Comment by gregorycarnegie** [comment]
@pedrohrcunha yes, and I have also tried it with --no-eta and --no-dupchecks together

**Comment by SonOfRome** [comment]
Hey there. I'm also into the comp. ;D Did it finally generate any passwords with 24 tokens? I didn't get it working or wasn't waiting long enough. No luck so far. Anyone knows if you can substitute a token like this
^3^tree ^17^tree ^22^tree
with a wordlist easily?

**Comment by gregorycarnegie** [comment]
I was able to get it working after simplifying the code. And bringing words together where necessary:

^5^bun ^5^bun
^5^cot ^6^cot

Becomes:
^5^buncot ^5^cotbun

And:
^10^woe ^11^woe ^13^woe ^21^woe ^23^woe

Becomes:
^10,11^woe ^13^woe ^21^woe ^23^woe

This reduces the number of arguments. And gets passwords generating within 20 minutes.

**Comment by Olegeekk** [comment]
not understend how make this tokens, can anyone help ? 
for example i have "4 symbols in my numeric password" 
how make token for generate passwords from 1111 to 9999 ??????

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022  and Gmail: walletsrecoveryservice@gmail.com
