### ISSUE TITLE
I recovered my password.. What's the next step?

### ISSUE THREAD

**Issue by HoplaGeiss** [gurnec/btcrecover#284]
I recovered my password with your tool.
What's the next step to look what's inside my wallet?
I ran your tool on a file called 'Bitcoin Wallet backup', but I can't remember where it comes from.

**Comment by vly3** [comment]
Do you not remember what wallet software you used to create the wallet?  Probably reinstall that software and put the backup wallet file in place of whatever new wallet file the software creates when you install it.

**Comment by HoplaGeiss** [comment]
No that's the issue. I can't remember the wallet software I used to create the wallet. Closing this issue, I will try the most common one until I find the good one.
