### ISSUE TITLE
[Feature Req] Electrum wallet with only imported keys

### ISSUE THREAD

**Issue by jamesearljones** [gurnec/btcrecover#29]
Hi,

Trying to recover a password on an Electrum wallet that was not created in the 'normal' way.

It's just a passworded Electrum wallet with an imported key. Btcrecover doesn't seem to be able to make heads or tails out of it. Instead of seed, etc, I just have 'keystore' and 'keypairs' section in the wallet. 

They look something like this:
    "keystore": {
        "keypairs": {
            "04d0074789a89ee39eef5cccf13d0c4aa02d6db4fc02ada2ee1354f6b50bca4204aa0f18f94ea1b88d0d81924
fe0d65dd5514db881b1158a53d072818ef6fa2ed9": "a5UBXagn/GdGHvCMsu25dCbpqZ21tiqyyFMjr8sTJwN0TbZDhu0yqaAiQ
MciO+5VNoy0S6SiN41rpCWoM1Hie47tVSB5jOJg43yeF667KCc="
        },
        "type": "imported"
    },

(Obviously changed/obfuscated)
Can btcrecover make use of these? 

Thanks

**Comment by jamesearljones** [comment]
After very little research Ive found it's the pubkey followed by the password. I'm going to see if I can just hack the extract script to go after this like it does the seed.

**Comment by gurnec** [comment]
You're running into two issues.

First is that btcrecover doesn't support the new wallet format introduced in Electrum 2.7. I've already been working on this a bit.

The second is that it doesn't support wallets with loose key pairs. I'll add this to the list. Unfortunately your idea of just hacking the extract script isn't enough, the return_verified_password_or_false also needs changes. I'll add this to the list....

**Comment by jamesearljones** [comment]
Indeed, I appreciate your taking the time to look at this. I do have a copy of it, pre-2.7.x. Can we work anything out with this or do we still have the loose keypair isse;

James

**Comment by gurnec** [comment]
I just uploaded a version which supports Electrum loose keypairs (for both the new 2.7 wallet format, and for the 2.0-2.6 format).

Could you please let me know how it works out for you, either way? Thanks!
