### ISSUE TITLE
Help Wanted - XLM Address

### ISSUE THREAD

**Issue by sp3sh** [gurnec/btcrecover#297]
Hello, I have an issue where my seed is incorrect. So far I have over 130k possible valid combinations and counting. I am using simple JS to output all possible valid combinations of my word set. My issue is I never used any other currency on my ledger except for Stellar Lumens / XLM. Could this application be adapted to XLM or is there a way i can verify my valid seeds generated against my XLM address. Its only 14k XLM but to me it is everything right now. Any help would be appreciated.

**Comment by vly3** [comment]
When I needed to recover my wallet from an incorrect phrase, I wrote a modification to Ian Coleman's BIP39 tool to automate inputting guesses to his tool, which worked.  Unfortunately, it does not have support for Stellar so my modification probably won't help you.  Here's the issue page regarding its lack of Stellar support.

https://github.com/iancoleman/bip39/issues/130

However, that issue page references these two projects as potentially helpful in adding Stellar support:

https://github.com/chatch/stellar-hd-wallet 

https://github.com/stellar-fox/redshift

You could probably modify either of those two projects to automate your guessing process.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
