### ISSUE TITLE
Need comand for run btcrecover on Kubuntu

### ISSUE THREAD

**Issue by tor888** [gurnec/btcrecover#3]
Hello.
I think maybe you've can help me...
I download the btcrecover and unzip home\btcrecover-master.(OS KUBUNTU)
Move into this folder wallet.dat.
Which comands i must type in the terminal for btcrecover.py  search password?
Where i can read this.
I no want take you time.but i no see any way.
Thanks.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
