### ISSUE TITLE
GPU support not working with suggested Windows PyOpenCL binaries

### ISSUE THREAD

**Issue by gurnec** [gurnec/btcrecover#30]
The installation documentation recommends downloading Windows PyOpenCL binaries [from here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl), however these binaries are currently not working with most Windows PCs.

If an immediate need for this is required before it's fixed, I have a workaround available on request.

**Comment by gurnec** [comment]
@cgohlke was kind enough to update the PyOpenCL binaries he maintains to support a wider range of Windows video drivers (Thanks!), so I'll close this issue after some minor doc updates.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
