### ISSUE TITLE
wallet.dat 2009

### ISSUE THREAD

**Issue by nekit44** [gurnec/btcrecover#310]
Sorry for my English.
I have a wallet.dat created in 2009. Can btcrecover decrypt it?

**Comment by ghost** [comment]
yes

**Comment by anhday22** [comment]
please inbox me

**Comment by nekit44** [comment]
> please inbox me

?

**Comment by anhday22** [comment]
I can help you please inbox fb.me/phamhoangmk

**Comment by kost123** [comment]
It can, if you still need help, let me know, cheers.

**Comment by nekit44** [comment]
> It can, if you still need help, let me know, cheers.

how?

**Comment by kost123** [comment]
How what?

**Comment by nekit44** [comment]
you help me? how?

**Comment by kost123** [comment]
By guiding you on how to recover your wallet file, have you tried at all to use it on btcrecover?

**Comment by nekit44** [comment]
yes, i sure is not real

**Comment by kost123** [comment]
What is not real? your wallet file? or btcrecover?

**Comment by nekit44** [comment]
decrypt is wallet.dat

**Comment by nekit44** [comment]
i am touched 1kkkk hash 
:)
hope is gone

**Comment by kost123** [comment]
Unfortunately I do not understand your english, but hope isn't gone.

**Comment by kost123** [comment]
If you truely believe hope is gone, send the wallet.dat file to kkonstanti@mail.ru and let me look at it, it's better than just believeing hope is gone.

**Comment by nekit44** [comment]
по русски)
я проверил много вариантов, если вы предлагаете брутфорс, то нет спасибо
у меня надежда уже покинула перебором получить доступ
2 фермы перебирали много месяцев, все без толку.

**Comment by kost123** [comment]
Я поправляю кошелек уже 6 лет, я очень хорош.

Я не могу помочь вам, если вы не готовы попробовать.

Я понимаю, вы чувствуете, что вся надежда потеряна.

**Comment by nekit44** [comment]
Вам нужен сам файл?

**Comment by kost123** [comment]
No, just  JohnTheRipper hash if you know how to do it, it's most safe for you.

I am not sure if JohnTheRipper will get the hash from a 2009 wallet is the problem, only you know that.

Otherwise I could manually extract the hash from the file.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by Delti42** [comment]
> Извините за мой английский.
> У меня есть файл wallet.dat, созданный в 2009 году. Может ли btcrecover его расшифровать?

Привет! Могу помочь в этом вопросе, если еще актуально.

**Comment by nekit44** [comment]
> > Извините за мой английский.
> > У меня есть файл wallet.dat, созданный в 2009 году. Может ли btcrecover его расшифровать?
> 
> Привет! Могу помочь в этом вопросе, если еще актуально.

Каким образом?

**Comment by btcexchanging** [comment]
if you haven't recovered your wallet, i can help you recover your wallet.
I have recovered most of the common wallets and recovery phrases for many users
you can reach me here at my telegram account:  @walletrecover

**Comment by AVotadlos** [comment]
> > > Извините за мой английский. 
> > > У меня есть файл wallet.dat, созданный в 2009 году. Может ли btcrecover его расшифровать?
> > 
> > 
> > Привет! Могу помочь в этом вопросе, если еще актуально.
> 
> Каким образом?

привет дружище, ну что ты как маленький, если там большая сумма к делу нужно подходить серьезно, если файл чужой, то можно забыть эту идею, хотя есть варианты подобрать пароль, но это очень сложно, если же файл твой, но ты забыл пароль, то тебе нужно вспомнить хотя бы какие там символы были, какое количество и тогда уйдут не месяцы на брутфорс, а возможно часы.

**Comment by nekit44** [comment]
> > > > Извините за мой английский.
> > > > У меня есть файл wallet.dat, созданный в 2009 году. Может ли btcrecover его расшифровать?
> > > 
> > > 
> > > Привет! Могу помочь в этом вопросе, если еще актуально.
> > 
> > 
> > Каким образом?
> 
> привет дружище, ну что ты как маленький, если там большая сумма к делу нужно подходить серьезно, если файл чужой, то можно забыть эту идею, хотя есть варианты подобрать пароль, но это очень сложно, если же файл твой, но ты забыл пароль, то тебе нужно вспомнить хотя бы какие там символы были, какое количество и тогда уйдут не месяцы на брутфорс, а возможно часы.

Ну прямо Америку мне открыл. Тема не актуальна

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
