### ISSUE TITLE
cyrillic passwords & tokens 

### ISSUE THREAD

**Issue by Olegeekk** [gurnec/btcrecover#326]
Hello, can you answer me, we have this future in btcrecover or no.
I think i have typed my password in Cyrillic symbols, im trying to brute with password list  & make tokens. What right way for this ? For passwords with russian language

**Comment by Olegeekk** [comment]
find thanks

**Comment by Olegeekk** [comment]
remove please

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
