### ISSUE TITLE
2,5 BTC reward! Multibit wallet blocked. 

### ISSUE THREAD

**Issue by deloxd** [gurnec/btcrecover#331]
Hey Guys,

I have  multibit wallet since 2012 that is locked and my password is unknown. In some winter evening I change password and I totally dont't remember ;/

I have some my old password list. 

I have this files.
.wallet
.key
.extract key
Maybe someone try crack my .key file. I also have an encrypted and unecrypted wallet that uses the same password. I offer a 2 Bitcoin bounty to whoever can crack the wallet.

I tried to crack but nothing of it
I try All A-Z, 0-9 to 1-7. And 20Gb of wordlist form some leaks. 

Thank

**Comment by desioner** [comment]
Ok, are you willing to share the wallet file for cracking? I have a great setup to assist with the bruteforce method formwallet files.

**Comment by Lahsini** [comment]
I may help. Send me an email lahsini.store@gmail.com and let's talk details.

**Comment by ashwilly** [comment]
Email cheng66@protonmail.ch, he once helped with recovering stolen funds from my wallet.

**Comment by anhday22** [comment]
Please inbox me. fb.me/recoverywallet or https://recoverywalletcrypto.com

**Comment by kost123** [comment]
If you want actual help and not be scammed by these dodgy posts, let me know.

**Comment by pesca-source** [comment]
Hello, If you want I can help you guiding you without having the files
Můžu ti pomoci

**Comment by deloxd** [comment]
> If you want actual help and not be scammed by these dodgy posts, let me know.



> Ok, are you willing to share the wallet file for cracking? I have a great setup to assist with the bruteforce method formwallet files.

**Comment by deloxd** [comment]
> Ok, are you willing to share the wallet file for cracking? I have a great setup to assist with the bruteforce method formwallet files.

Hi I can share extract only

**Comment by cryptoprogramer** [comment]
hi i would also like to bruteforce it share the extract +password hints with me

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
you can contact https://twitter.com/Btc2doge he has recovered many btc.  https://btc2doge.com/rewiews/
