### ISSUE TITLE
run-all-tests.py returns "ImportError: No module named CppBlockUtils"

### ISSUE THREAD

**Issue by synchronizing** [gurnec/btcrecover#34]
I can't seem to find any fix online for the missing `CppBlocksUtils`. Any help would be appreciated. I'm attempting to decrypt a Electrum wallet 

```
Traceback (most recent call last):
  File "run-all-tests.py", line 54, in <module>
    from btcrecover.test import test_passwords, test_seeds
  File "/Users/felipefaria/Desktop/btcrecover-master/btcrecover/test/test_seeds.py", line 39, in <module>
    from .. import btcrseed
  File "/Users/felipefaria/Desktop/btcrecover-master/btcrecover/btcrseed.py", line 38, in <module>
    from CppBlockUtils import CryptoECDSA, SecureBinaryData
ImportError: No module named CppBlockUtils
```

## Edit: Fixed

I delved into the code and found that `run-all-tests.py` is dependent on Armory being install according to `btcrpass.py`, no matter what wallet you intend on decrypting. 

```
    elif sys.platform == "darwin":  # untested
        sys.path.append("/Applications/Armory.app/Contents/MacOS/py/usr/lib/armory")
    is_armory_path_added = True
```

After installing Armory.app this specific error was fixed.

**Comment by gurnec** [comment]
That's definitely a unit test bug IMO, those tests shouldn't run if Armory isn't installed (and aren't even relevant if you don't need to run seedrecover.py; seedrecover needs Armory, but btcrecover.py doesn't need it). I'll look into fixing this.

Also, thanks for verifying that the Armory loading code works correctly on OS X (that's something I've never actually tested myself)!

**Comment by synchronizing** [comment]
I was going to take a look at it later today and hopefully had a merge by tomorrow morning, I'm glad you took care of it. I'll run the new build later and let you know how that goes.

**Comment by gurnec** [comment]
> Let me also plug-in here a "thank you", as I was actually able to recover my wallets password.

That's great to hear!

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
