### ISSUE TITLE
5 btc reward issue

### ISSUE THREAD

**Issue by bitconnectinfs** [gurnec/btcrecover#346]
closed

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
you can contact https://twitter.com/Btc2doge
