### ISSUE TITLE
How can I try all possible capitalisations? Reward if found

### ISSUE THREAD

**Issue by bitconnectinfs** [gurnec/btcrecover#347]
How can I try all possible capitalisations of my tokens? for example, if I use the token "he", the script must  try "he", "HE", "He", hE"
I want this to apply to all capitalisations, BTC reward if it's found.
Let me know please :) telegram @lostsomebtc

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
