### ISSUE TITLE
Using BIP 39 recovery and getting error.

### ISSUE THREAD

**Issue by satoshidoriannakamoto** [gurnec/btcrecover#358]
I have the 24 word seed.  It is the passphrase I am trying to guess.  I have three bitcoin public addresses.  When I run BIP 39 using this command line I get an error.

`python btcrecover.py --bip39 --tokenlist t token.txt`

Error I get:

`An entered address is invalid (not a Bitcoin P2PKH address; version byte is 0x05)` 

It is a public btc address.  I have three of them and all three generate the same error.

**Comment by fran2k** [comment]
Script only supports legacy addresses (P2PKH), you probably have a segwit compatible (P2SH) or native (bech32) address.

**Comment by ghost** [comment]
Use https://github.com/3rdIteration/btcrecover

**Comment by satoshidoriannakamoto** [comment]
> Use https://github.com/3rdIteration/btcrecover

Ok, thanks. This works.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
