### ISSUE TITLE
Litecoin Core

### ISSUE THREAD

**Issue by zex333** [gurnec/btcrecover#359]
Is litecoin core supported? and if so, how do you configure the program for it? I have tried using my wallet.dat file, and every wallet option with my address but I get errors for each of them.
thanks

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
