### ISSUE TITLE
download-blockchain-wallet.py fails when email or IP verification is enabled

### ISSUE THREAD

**Issue by gurnec** [gurnec/btcrecover#36]
When email or IP verification is enabled, the script asks you to check your email. When you click on the link in your email from blockchain.info, click Authorize, and then tell the script to retry the download, it should complete the download (or move on to the 2FA step if necessary). Instead it tells you  to check your email again.

**Comment by DENYHAX** [comment]
Same problem, after authorizing the script to login it is still asking for authorization.  please fix asap

**Comment by gurnec** [comment]
I believe this should now be fixed, please let me know if it's not working for you.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
