### ISSUE TITLE
wrong number of operations?

### ISSUE THREAD

**Issue by Mathematician09183** [gurnec/btcrecover#363]
Hello
I am not sure if I calculate something wrong or btcrecovery. Let's say I have a list:
+ ^X
+ ab ac
+ x
+ %3[abc]
+ %3[cde]
+ %[ab]
+ %[xyz]
+ %[mnop]
As I understand there are 420 permutations (because we have always 1st token at the beginning). And for each permiutations (ignoring duplicates) we have
2*(3*3*3)*(3*3*3)*2*3*4 possibilities, which gives 14696640 tries.
I see btcrecovery did already 80000000 tries and still works... Why?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
