### ISSUE TITLE
GPU search does not work

### ISSUE THREAD

**Issue by Mathematician09183** [gurnec/btcrecover#364]
Using GPU shows wrong number of operations and does not find password:

`$ python3 btcrecover.py --wallet=wallet.dat --tokenlist=test.txt --dsw --no-eta --enable-gpu

Starting btcrecover 1.2.0-Cryptoguide on Python 3.6.9 64-bit, 21-bit unicodes, 64-bit ints
btcrecover.py: warning: --no-eta without --no-dupchecks can cause out-of-memory failures while searching
Wallet difficulty: 277,932 SHA-512 iterations
2020-06-14 16:28:47 : Using 2 OpenCL devices:
  ALL | GPU GeForce GTX 1070 Ti
  ALL | GPU GeForce GTX 1070 Ti
| 275222  elapsed: 0:00:03  rate:  69.59 kP/s
Password search exhausted

$ python3 btcrecover.py --wallet=wallet.dat --tokenlist=test.txt --dsw --no-eta

Starting btcrecover 1.2.0-Cryptoguide on Python 3.6.9 64-bit, 21-bit unicodes, 64-bit ints
btcrecover.py: warning: --no-eta without --no-dupchecks can cause out-of-memory failures while searching
Wallet difficulty: 277,932 SHA-512 iterations
2020-06-14 16:28:57 : Using 12 worker threads
- 2  elapsed: 0:00:00  rate:   5.96  P/s

If this tool helped you to recover funds, please consider donating 1% of what you recovered, in your crypto of choice to:
BTC: 37N7B7sdHahCXTcMJgEnHz7YmiR4bEqCrS
BCH: qpvjee5vwwsv78xc28kwgd3m9mnn5adargxd94kmrt
LTC: M966MQte7agAzdCZe5ssHo7g9VriwXgyqM
ETH: 0x72343f2806428dbbc2C11a83A1844912184b4243

Find me on Reddit @ https://www.reddit.com/user/Crypto-Guide

You may also consider donating to Gurnec, who created and maintained this tool until late 2017 @ 3Au8ZodNHPei7MQiSVAWb7NB2yqsb48GW4

Password found: '111'`

for tokenlist:
`
+ ^1^1
1
1
`

password hash: YmM6Z3JBH5FuxI4myS9+eI0KM66zfPX3ibGodvQQRzr41W+bpAISYTR5okw4BAAyym07

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
