### ISSUE TITLE
hello all, someone who can help me please

### ISSUE THREAD

**Issue by kerstui** [gurnec/btcrecover#367]
Hello all you guys/irls, i have a problem.
im runing btcrecover, need to get a password, The onlu thing i know is the password have 9 caracters, 
So i put in token.txt   %9in  and here i got the problem, because start and them folow do this 
aaaaaafli
aaaaaaflo ....n
 i read all tutorial (im new in all this about cmd using), im using cmd in windows 10, and dont find nothing to avoid "aaaaa" together, im sure have 2 or  "a", but no all that, 
I know when change to "b" will do the same, 
could you please tellme if i can fix it and btcrecover run 9 caracters, only letters, maby max 3a, i and e, but no "o" and "u", and test all others caracters?, if you know what i try to do, 
If can help me to do this with another way please help me

**Comment by kerstui** [comment]
.....

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
