### ISSUE TITLE
Counting passwords ... 290,200,000 ETA: 7.0 days and counting btcrecover.py: error:

### ISSUE THREAD

**Issue by kerstui** [gurnec/btcrecover#370]
Counting passwords ... 290,200,000 ETA: 7.0 days and counting btcrecover.py: error: at least 290,200,000 passwords to try, ETA > max_eta option (168 hours), exiting  
Hello Sr. could you please tellme how i fix this, i mean, there is a way to make it run frst 5hs, them from 5hs to 10hs, .......n?  Thankyou for take time to read

**Comment by kerstui** [comment]
.

**Comment by anywalletrecovery** [comment]
did you mange to recover your coins? I can bruteforce your wallet and solve its problem.

if you have still wallet problem I might help here is my telgram id

@walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
