### ISSUE TITLE
Electrum 1 seed

### ISSUE THREAD

**Issue by ghost** [gurnec/btcrecover#387]
Hi there, I have an old electrum seed that doesn't work. I figure I need to try different combinations of the seed as I can vaguely remember swapping words around when I saved it. I tested your tool on a generated electrum 1 seed and just moved the last word to the front, but your tool didn't find the correct seed. Any help will be appreciated with a reward :)

**Comment by ghost** [comment]
OK after more testing I get it , it must have been in docs somewhere, but the error has to be two words next to each other swapped. Any further and it doesn't find it. For a 12 word seed this trying all the combinations would be 479,001,600 (or around 150 days on my i7). I'll try and modify the code and maybe run this on an online rig.

**Comment by ghost** [comment]
Ah I see I don't even have to do the above. https://www.youtube.com/watch?v=ruSF8OKwBRk If this works, reward coming your way 👍

**Comment by anywalletrecovery** [comment]
did you mange to recover your coins? I can bruteforce your wallet and solve its problem.

if you have still wallet problem I might help here is my telgram id

@walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by ipensatori** [comment]
Do you not have access to a GPU to help speed things up considerably?
