### ISSUE TITLE
Error trying to decrypt first password for Blockchain.info wallet

### ISSUE THREAD

**Issue by YvonFortier** [gurnec/btcrecover#40]
Hello!

When running:

`python btcrecover.py --wallet wallet.aes.json --tokenlist tokens`

I'm getting
`Traceback (most recent call last):
  File "btcrecover.py", line 35, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "/home/user/btcrecover-master/btcrecover/btcrpass.py", line 3420, in parse_arguments
    parse_tokenlist(tokenlist_file, tokenlist_first_line_num)
  File "/home/user/btcrecover-master/btcrecover/btcrpass.py", line 3691, in parse_tokenlist
    if line.startswith("#"):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
`

Any ideas? File was downloaded with your tool.

Thank you!

**Comment by YvonFortier** [comment]
Solved! Problem was the file encoding:

https://github.com/gurnec/btcrecover/issues/22#issuecomment-229782285

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
