### ISSUE TITLE
Using numbers with anchors

### ISSUE THREAD

**Issue by TheAlexPorter** [gurnec/btcrecover#410]
Hi all,

I'm trying to anchor 123 to the beginning of the password string. I've been doing `^123` which is causing an error since it thinks I want to use a positional or middle anchor. But that isn't the case. What do I need to do to escape the number so I avoid this issue, but can still prepend my passwords with 123?

Thanks for the help!

**Comment by nicoschtein** [comment]
Hi!

You should try this other fork:

https://github.com/3rdIteration/btcrecover

And do something like:

`^1^123`

Hope that helps!

**Comment by TheAlexPorter** [comment]
> Hi!
> 
> You should try this other fork:
> 
> https://github.com/3rdIteration/btcrecover
> 
> And do something like:
> 
> `^1^123`
> 
> Hope that helps!

Thank you! I'll give this a go tonight. I appreciate the help, this will lower the number of passwords I'm generating significantly.

**Comment by TheAlexPorter** [comment]
This worked. Thanks again @nicoschtein!
