### ISSUE TITLE
I have 2 questions...

### ISSUE THREAD

**Issue by MojoMoe** [gurnec/btcrecover#423]
Fantastic program! 
2 questions:

Any chance of getting this wonderful program upgraded to Python 3.x ? The GPU option doesn't seem to work for me (AMD 7970 HD)
If I have a list of say 500 words (dictionary/wordlist) that I would like to add a suffix of 6 digits to each word in the dictionary, how can I do this? I know I can do one word at a time using the 'token' file option, but is it possible to do all 500 words without having to repeat this process by manually editing the tokens.txt file 500 times for each word?

**Comment by nicoschtein** [comment]
Hi!

Try using this other fork:


GitHub.com/3rditeration/btcrecover

And the updated docs https://btcrecover.readthedocs.io/

**Comment by MojoMoe** [comment]
> Hi!
> 
> Try using this other fork:
> 
> GitHub.com/3rditeration/btcrecover
> 
> And the updated docs https://btcrecover.readthedocs.io/

Thanks for that. I have the Python 3.x version up and running now, however I am still unsure how I can append a number at the end of every word in my wordlist, starting from the number 1, all the way up to 6 digits being appended to every word. I know that will take a while.

**Comment by 3rdIteration** [comment]
@MojoMoe see https://btcrecover.readthedocs.io/en/latest/tokenlist_file/#expanding-wildcards

**Comment by MojoMoe** [comment]
Thank you very much for your responses. Much appreciated. I will close this issue now :)

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
