### ISSUE TITLE
(not so) possible wallet file

### ISSUE THREAD

**Issue by tropical95** [gurnec/btcrecover#431]
I found an extensionless file (62kB) that might be my lost dogecoin wallet. Or at least I hoped so. But Following the installation steps for dogecoin core (think I made the wallet back in 2014 using the official dogecoin desktop app) this is all I get:
```
Starting btcrecover 0.17.10 on Python 2.7.18 64-bit, 16-bit unicodes, 32-bit ints
btcrecover.py: error: unrecognized wallet format; heuristic parser(s) reported:
    WalletPywallet: Unrecognized pywallet format (does not look like ASCII text)
    WalletMultiBitHD: MultiBit HD wallet files must be named mbhd.wallet.aes
    WalletBlockchain: Can't base64-decode Blockchain wallet: Incorrect padding
```
Are there any ways to find out whether my extensionless file is a wallet? Trying to reimport it into the current dogecoin wallet desktop app got me a "wallet corrupt salvage failed” Error. Could an older client version work? Where would I get the one I need for my 2014 oldschool wallet?

Also my run-all-tests looked like this:

```
** Testing in ASCII character mode **
...
Ran 293 tests in 24.933s

OK (skipped=68)

** Testing in Unicode character mode **
...
Ran 293 tests in 29.279s

OK (skipped=44)

warning: skipping seed recovery tests (can't find prerequisite coincurve)

*** Full Results ***

Ran 586 tests in 54.220s

OK (skipped=112)

Press Enter to exit ...
```
But I do not think that this causes the "problems"

Thanks for any intel, feel free to redirect me to a better place for these questions :D

**Comment by anywalletrecovery** [comment]
check the content of file to see if it is a wallet file or not

**Comment by tropical95** [comment]
I found out that what I tried to decrypt was actually just an old NFS MW savefile. But thanks!

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by SiraxRS** [comment]
Hi, I got same problem can you help with the solution? How to check what I'm trying to decrypt?

**Comment by SiraxRS** [comment]
> I found out that what I tried to decrypt was actually just an old NFS MW savefile. But thanks!

Hi, Can you help?

```
C:\btcrecover-master>C:\Python27\python btcrecover.py --tokenlist token.txt --wallet btc.dat
Starting btcrecover 0.17.10 on Python 2.7.16 64-bit, 16-bit unicodes, 32-bit ints
btcrecover.py: error: unrecognized wallet format; heuristic parser(s) reported:
    WalletPywallet: Unrecognized pywallet format (does not look like ASCII text)
    WalletMultiBitHD: MultiBit HD wallet files must be named mbhd.wallet.aes
    WalletMsigna: Not an mSIGNA wallet: no such table: Keychain
    WalletBlockchain: Encrypted Blockchain data length is not divisible by the encryption blocksize (16)
    WalletBither: Not a Bither wallet: no such table: addresses, no such table: password_seed
```

Just created a wallet now for test as I have some old wallet without access and try to work out if the method is working.
