### ISSUE TITLE
Can't use on old Dogecoin wallet?

### ISSUE THREAD

**Issue by jinatonic** [gurnec/btcrecover#432]
I have a valid dogecoin wallet (imported it into Dogecoin Core and was able to see the transaction history). This wallet was created back in 2014 or so. However, when trying to use btcrecover, I get the 
```
ValueError: Encrypted master key #1 not found in the Bitcoin Core wallet file.
(is this wallet encrypted? is this a standard Bitcoin Core wallet?)
```

Any way to make it work with the old dogecoin wallet?

**Comment by buckiboy** [comment]
Hi, did you manage to get this resolved? I am getting the same issue. 

many thanks.

**Comment by buckiboy** [comment]
So figured it out. That message means that there is no password set for the wallet :)

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
