### ISSUE TITLE
Can I use this to recover Binance smart chain wallet?

### ISSUE THREAD

**Issue by tareqanwar** [gurnec/btcrecover#434]
I have 12 words but its not working. May be I wrote it in wrong order

**Comment by anywalletrecovery** [comment]
did you mange to recover your coins? I can bruteforce your wallet and solve its problem.

if you have still wallet problem I might help here is my telgram id

@walletrecover

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
