### ISSUE TITLE
Regex for secondaray password of Blockchain.info wallet

### ISSUE THREAD

**Issue by bslackp** [gurnec/btcrecover#437]
This will help a lot of people who want to brute-force their wallet if there are known regex for passwords.. Like min-max length, special characters and capital or small characters and numbers, etc.. I was not able to find info about this on blockchain.com or from their support. If any one have idea about this, then can you update in doc of password recovery section of Blockchain.info wallet.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
you can contact https://twitter.com/Btc2doge to decrypt your wallet. this is caused by a bug in the early wallets in 2016.
