### ISSUE TITLE
who can crack blockchain wallet , I will pay with bitcoin

### ISSUE THREAD

**Issue by rfakit** [gurnec/btcrecover#448]
close it

**Comment by cryptoprogramer** [comment]
if you mean the wallet.dat files being sold over the internet, they are all fake and useless

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com

**Comment by doge2021** [comment]
you can contact https://twitter.com/Btc2doge to decrypt your wallet. this is caused by a bug in the early wallets in 2016.
