### ISSUE TITLE
Can't download Pycrypto

### ISSUE THREAD

**Issue by S1n86** [gurnec/btcrecover#459]
Hello. I can't acces to http://www.voidspace.org.uk/python/modules.shtml#pycrypto because I have problems with my DNS. Can someone send me Pycrypto2.6 64x for 2.7 python. My discord is S1n#8238. I would be grateful if you could help. Sorry if this is a useless post.
![Снимок экрана (14)](https://user-images.githubusercontent.com/81864722/139747478-585de5d3-b836-40d8-91af-a67527f93dd3.png)

**Comment by S1n86** [comment]
Uh ok. I found A link to download Pycrypto. Sorry for this post

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
