### ISSUE TITLE
Btcrecover doesn't work

### ISSUE THREAD

**Issue by S1n86** [gurnec/btcrecover#460]
Hi I get this issue when I try to use btc recover.
Can someone help me?

C:\Users\Вадим\OneDrive\Рабочий стол\btcrecover-master>C:\Python27\python btcrecover.py
Starting btcrecover 0.17.10 on Python 2.7.18 64-bit, 16-bit unicodes, 32-bit ints
Read additional options from tokenlist file: --wallet wallet.dat --enable-gpu
Traceback (most recent call last):
  File "btcrecover.py", line 37, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\┬рфшь\OneDrive\╨рсюўшщ ёЄюы\btcrecover-master\btcrecover\btcrpass.py", line 3561, in parse_arguments
    loaded_wallet.init_opencl_kernel(devices, args.global_ws, args.local_ws, args.int_rate, *extra_opencl_args)
  File "C:\Users\┬рфшь\OneDrive\╨рсюўшщ ёЄюы\btcrecover-master\btcrecover\btcrpass.py", line 835, in init_opencl_kernel
    os.path.join(os.path.dirname(os.path.realpath(__file__)), "sha512-bc-kernel.cl"))
  File "C:\Python27\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 7: ordinal not in range(128)

And if I will be able to recover my passphrase I will send you some bitcoins

**Comment by cryptoprogramer** [comment]
i can guide you to do the recovery
but be informed that this program doesn't work any more
if you even include correct password in the file, it wont find password

**Comment by S1n86** [comment]
I already installed new version of btcrecover and found my password. Ty for reply
