### ISSUE TITLE
GPU not working as expected??

### ISSUE THREAD

**Issue by khrizo** [gurnec/btcrecover#50]
Working on a doge core wallet
Dummy password list

123
12345
4321 <-- right pass

Regular search finds the password.
```
Password found: '4321'
```

While enabling GPU: --enable-gpu --global-ws 4096 --local-ws 256 --no-eta 
```
Using OpenCL GPU AMD Radeon HD Tahiti XT Prototype Compute Engine
| 3  elapsed: 0:00:04  rate:   1.07  P/s
Password search exhausted
```

**Comment by gurnec** [comment]
Sorry for the late response, but did you end up figuring out what the issue was? If it's a bug in btcrecover, I'd still be interested in trying to fix it... thanks.
