### ISSUE TITLE
exodus wallets recover ? 

### ISSUE THREAD

**Issue by KobraIQ** [gurnec/btcrecover#500]
I forgot my exodus wallet password and info and i have all info backed up but it's all encrypted i manged to extract the hash form the files using hashcat but don't know where to go next . Files like "seed.seco" and "two-factor.seco" "info.seco" and the "passphrase.json" and i stumbled upon this https://github.com/ExodusMovement/seco-file and dont know how to use it any help ??

![him2](https://github.com/gurnec/btcrecover/assets/112991571/71cf8ef6-8fb5-44d0-bce6-33a64c05c68b)

**Comment by YrnBilly** [comment]
How can I get the 12 phrase
