### ISSUE TITLE
Passwd Hash Length - Blockchain.info

### ISSUE THREAD

**Issue by 2b3pro** [gurnec/btcrecover#55]
Suppose I have both the hashes for my main password and my second password for a blockchain.info wallet. Do the lengths of the hashes indicate whether one password is possibly longer than the other? Currently the 2nd hash is longer than the 1st. Thoughts?

**Comment by gurnec** [comment]
I'm afraid I don't understand....

A Blockchain,info wallet file doesn't contain the hash of the main password. The only way to check if the main password is correct is to attempt to decrypt the wallet file using the main password, and see if the result looks like JSON plaintext.

Once decrypted, the JSON plaintext _does_ contain the hash of the second password (it's called the `dpasswordhash`), but that still leaves me a bit confused...?

**Comment by 2b3pro** [comment]
Sorry, please disregard the question. I was trying to brute force the second password, and wondered if the hash of the second password obtained via the extract scripts gave me any clue about possible password length.

**Comment by gurnec** [comment]
I definitely misunderstood, but now I understand what you were asking. Although you don't need the answer any longer, just for the record it's "no", there's no way to deduce the password length from *any* of the data retrieved by the various extract scripts.

**Comment by cprkrn** [comment]
Sorry if this isn't the right place- I have the first password, 2fa, and the second password hash. Trying to use hashcat to undo the hash with these:

1400 | SHA-256                                          | Raw Hash
1410 | sha256($pass.$salt)                        | Raw Hash, Salted and/or Iterated
1420 | sha256($salt.$pass)                        | Raw Hash, Salted and/or Iterated
1430 | sha256(utf16le($pass).$salt)          | Raw Hash, Salted and/or Iterated
1440 | sha256($salt.utf16le($pass))          | Raw Hash, Salted and/or Iterated

Just wondering if this is even possible or if I'm wasting my time here. Feels like I'm really close to cracking it but it's too long of a password for me to bruteforce locally. 

Related: https://stackoverflow.com/questions/37181281/how-do-you-keep-track-of-your-comments-in-issues-on-github

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
