### ISSUE TITLE
Pyopencl on Ubuntu 17.04 

### ISSUE THREAD

**Issue by tor888** [gurnec/btcrecover#59]
Hello.
How install pyopencl on Ubuntu 17.04?

r@r-System-Product-Name:~/bt$ python btcrecover.py --wallet wallet.dat --tokenlist token13.txt --enable-gpu
Read additional options from tokenlist file: --autosave progress.sav --pause
btcrecover.py: warning: No module named pyopencl
btcrecover.py: error: no supported GPUs found
Press Enter to exit ...
r@r-System-Product-Name:~/bt$ python btcrecover.py --wallet wallet.dat --tokenlist token13.txt --enable-gpu
Read additional options from tokenlist file: --autosave progress.sav --pause
btcrecover.py: warning: No module named pyopencl
btcrecover.py: error: no supported GPUs found
Press Enter to exit ...

**Comment by TTN-** [comment]
if you do `apt search pyopencl` you'd find there's a package: `python-pyopencl` that you can install.

Do: `sudo apt-get install python-pyopencl`

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
