### ISSUE TITLE
How to escape $ char?

### ISSUE THREAD

**Issue by TTN-** [gurnec/btcrecover#60]
How do I escape the $ char? I can't figure it out I've read the tutorial carefully.

The reason I'm after this is because my S's could be s S or $.

**Comment by gurnec** [comment]
As long as the `$` isn't at the end of a token, it doesn't need to be escaped. Thus you could use a wildcard such as `%[sS$]`, with no escaping required, to represent one of those three characters.

You can also look at [Typos Maps](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#typos-map) for a different way of doing this sort of thing, which may or may not be easier if you're doing other such substitutions.

If you want the gory details on escaping (which I admit could be easier), [see here](https://github.com/gurnec/btcrecover/blob/master/docs/Limitations_and_Caveats.md#delimiters-spaces-and-special-symbols-in-passwords).

**Comment by TTN-** [comment]
Thanks!
