### ISSUE TITLE
Not checking all passwords from wordlist

### ISSUE THREAD

**Issue by Flix666** [gurnec/btcrecover#68]
Hi,

I'v created custom passwordlist, it contains 901 lines/passwords.
But when I use it on my wallet.dat file, btcrecover only checks 885 passwords.
Can someone explain me why?

I'v attached this passwordlist.

[12345.txt](https://github.com/gurnec/btcrecover/files/1061521/12345.txt)

**Comment by gurnec** [comment]
btcrecover isn't checking the duplicates; these 16 lines appear twice in your file:
```
^&
^%
!@
(*
@!
@#
$#
$%
*(
*&
&^
&*
#@
#$
%^
%$
```

If you really want btcrecover to try them twice, tell it not to check for duplicates by adding `--no-dupchecks` to the command line.

**Comment by Flix666** [comment]
Sorry, my mistake :)

Thank you for quick reply.

I'm closing this thread.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
