### ISSUE TITLE
Is there any way to provide information on the order of tokens aside from absolute position?

### ISSUE THREAD

**Issue by PLAAND** [gurnec/btcrecover#69]
For instance, if I know that my password must be in a particular order, or that certain orders of tokens are definitely invalid, is there a way to ensure that btcrecover attempts only combinations in the correct order?

I have, for example a similar Tokens file to this:

```
+ ^Token1%s
^2^Tok2.%s ^2^Tok2%s ^2^Tk2%s ^2^Token2%s ^2^tok2.%s ^2^tok2%s ^2^tk2%s 
^2,3^Token3%s ^2,3^token3%s ^2,3^Tokem3%s ^2,3^tokem3%s 
+ ^2,4^Token4%s ^2,4^token4%s ^2,4^Token4,%s ^2,4^token4,%s
+ ^3,5^Tok5.%s ^3,5^Tok5%s ^3,5^tok5.%s ^3,5^tok5%s ^3,5^Token5%s ^3,5^token5%s 
+ ^4,6^Token6%s ^4,6^Token6,%s ^4,6^Token6 ^4,6^Token6, Token6$
```

And so on. 

Is there any way to communicate to btcrecover that tokens, if they appear, must be in a particular order rather than just in certain positions? Because as I've created my tokens file it creates outputs such as: "Token1 Token5 Token6 Token4" that I know must be incorrect but are valid according to the positional notation that I've input.

Thanks!

**Comment by gurnec** [comment]
Would something [like this](https://github.com/gurnec/btcrecover/blob/8edea3c33e2c787b2ec886e25bf34820c6c81661/TUTORIAL.md#relative-anchors) be flexible enough to meet your needs?

(It's not implemented so don't bother trying it yet, I'm just asking!)

**Comment by PLAAND** [comment]
That looks perfect actually.

**Comment by gurnec** [comment]
This should be working now, let me know if you run into any problems.
