### ISSUE TITLE
Providing known address to remove false positives

### ISSUE THREAD

**Issue by kost123** [gurnec/btcrecover#72]
Would this be possible for things such as bitcoin wallet for android or multibit keys?

**Comment by gurnec** [comment]
OK, so the false positive rate for MultiBit key files (which includes Bitcoin Wallet for Android backup passwords) has now been reduced from 1 in 3⋅10<sup>11</sup> to 1 in 1.5⋅10<sup>19</sup>. False positives should occur 50 million times less frequently than they currently do; so practically never.

If you do see one though, let me know, it could be a bug in the new code.

**Comment by kost123** [comment]
Very well done, I will let you know how it goes.

**Comment by gurnec** [comment]
Please do, and good luck!
