### ISSUE TITLE
Warning: DLL load failed: the specified module could not be found

### ISSUE THREAD

**Issue by tigbitties** [gurnec/btcrecover#77]
I've got the libsodium.dll file in the C:\Python27 directory. What Am I doing wrong?

I've installed Microsoft Visual C++ 2015 Redistributable Update 3

**Comment by gurnec** [comment]
Are you certain you've chosen the libsodium.dll file which matches up with your version of Python (both must be 32-bit *or* both must be 64-bit)?

Also, I just updated the docs to use the newest version of libsodium (which also requires the newest version of the MSVC++ redistributable, also updated in the docs). Could try installing them if you're still having trouble?

**Comment by tigbitties** [comment]
I actually tried both 32 and 64  bit... I'm going to start over. I'll post an update once I can focus on it more and get started. Thanks.
