### ISSUE TITLE
Password minimum/maximum length

### ISSUE THREAD

**Issue by ghost** [gurnec/btcrecover#8]
Is there any way to specify a minimum or maximum password length when using tokens to generate a password list? --max-tokens and --min-tokens don't quite trim down the possibilities enough.

For example if I know the password is 10-15 characters and I have a list with tokens 1-8 characters long, combining two 8-character tokens will make a useless password guess, but there are potentially usable passwords from combining up to eight tokens (one 8-char and seven 1-chars).

Thanks for all the detailed docs!

**Comment by mikefiatx19** [comment]
using the expression above could you limit the search to only 19 or 20 characters?
