### ISSUE TITLE
recovering seed nano ledger wallet

### ISSUE THREAD

**Issue by hectorniyan** [gurnec/btcrecover#80]
Hello, I really need help. I am opening a new ticket because I fear that my last post on this subject may have been missed as it was a continuation of an older thread. Apologies if this results in irritating duplication. 

The situation is as follows:

    I have the receiving BTC address which was used to transfer BTC to the nano ledger wallet.
    First dialog box I clicked cancel for "xpub" address
    entered one of the BTC addresses used
    entered "5" into next dialog -- I don't know how many addresses were used (is this critical?)
    entered best guess for 24 word seed
    and got the following:

~/btcrecover-master$ python seedrecover.py
Using the 'en' wordlist.
Phase 1/3: up to 2 mistakes, excluding entirely different seed words.
Using 4 worker threads
24820 of 24820 [#####################################################] 0:00:00,
Seed not found
Phase 2/3: 1 mistake which can be an entirely different seed word.
Using 4 worker threads
49152 of 49152 [#####################################################] 0:00:01,
Seed not found
Phase 3/3: up to 2 mistakes, 1 of which can be an entirely different seed word.
Counting passwords ...
Done
Using 4 worker threads
10714631 of 10714631 [###############################################] 0:07:02,
Seed not found, sorry...

Press Enter to exit ...Process PoolWorker-10:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python2.7/multiprocessing/pool.py", line 102, in worker
task = get()
File "/usr/lib/python2.7/multiprocessing/queues.py", line 380, in get
rrelease()
KeyboardInterrupt
----------------
Anything I have done wrong? Do you have any further insight you can give to help me?

Really appreciate it if you can. Quite a lot of money in play here.

Thank you!
@hectorniyan

**Comment by gurnec** [comment]
Those error messages can be safely ignored; it's just complaining about not being able to shut down the background worker threads correctly (I'm not sure why it can't, but it's not important).

I just responded in the original issue, so I'm closing this one (you can respond over there too).

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

You can contact us on https://keychainx.io or send mail to help@keychainx.io

**Comment by makmour** [comment]
Blocked and reported.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
