### ISSUE TITLE
 I have wallet.dat file when i run btcrecover.py then this error shows

### ISSUE THREAD

**Issue by qasimilyas99** [gurnec/btcrecover#85]
I have wallet.dat file when i run btcrecover.py then this error shows >>

`encrypted_master_key, self._salt, method, self._iter_count = struct.unpack_from(b"< 49p 9p I I", mkey)
struct.error: unpack_from requires a buffer of at least 66 bytes`

**Comment by gurnec** [comment]
Are you using Bitcoin Core, or an alternative? What's the full version (it's the first line from the `Help` -> `About Bitcoin` menu option)?

**Comment by qasimilyas99** [comment]
Q: Are you using Bitcoin Core
Ans: Yes.

**Comment by gurnec** [comment]
What about this question:

> What's the full version (it's the first line from the Help -> About Bitcoin menu option)?

Also, do you receive a warning when you run btcrecover which looks like this?

> warning: bsddb (Berkeley DB) module not found

**Comment by qasimilyas99** [comment]
I'm currently using 
Bitcoin Core version 0.14.2
Qt version 5.7.1

**Comment by qasimilyas99** [comment]
`Read additional options from tokenlist file: --wallet wallet.dat
Traceback (most recent call last):
  File "C:\Users\admin\Downloads\btcrecover-master\btcrecover.py", line 35, in <module>
    btcrpass.parse_arguments(sys.argv[1:])
  File "C:\Users\admin\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 3362, in parse_arguments
    load_global_wallet(args.wallet)
  File "C:\Users\admin\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 218, in load_global_wallet
    loaded_wallet = load_wallet(wallet_filename)
  File "C:\Users\admin\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 199, in load_wallet
    return wallet_type.load_from_filename(wallet_filename)
  File "C:\Users\admin\Downloads\btcrecover-master\btcrecover\btcrpass.py", line 753, in load_from_filename
    encrypted_master_key, self._salt, method, self._iter_count = struct.unpack_from(b"< 49p 9p I I", mkey)
struct.error: unpack_from requires a buffer of at least 66 bytes`

**Comment by qasimilyas99** [comment]
Q: Also, do you receive a warning when you run btcrecover which looks like this?
Ans: No.

**Comment by qasimilyas99** [comment]
My wallet.dat file is old.

**Comment by gurnec** [comment]
OK, so I can't be sure, but my best guess right now is that you have a corrupted wallet.dat file. If you have a different backup, please give it a try first.

If not, you can try to use Bitcoin Core's `-salvagewallet` feature. Run this from the command line:

    "C:\Program Files\Bitcoin\bitcoin-qt.exe" -salvagewallet

(The location of your `bitcoin-qt.exe` may differ.) It will make a backup of your wallet.dat file under a different name (but in the same `C:\Users\admin\AppData\Roaming\Bitcoin` folder), and then it will try to fix the wallet.dat file.

If this doesn't work, you may want to look into Pywallet, specifically take a look at [this post to attempt to scan a wallet.dat for keys and construct a new one](https://bitcointalk.org/index.php?topic=34028.msg17452093#msg17452093).

Finally, if you'd like to, you can send me the output from a slightly modified btcrecover extract script, and I can try to make some sense out of it. First, install a decent text editor such as [Notepad++](https://notepad-plus-plus.org/download/) (this won't work with the built-in Notepad, although the built-in WordPad might work if you really don't want to download Notepad++). Next, using Notepad++, open the `extract-bitcoincore-mkey.py` file inside the `extract-scripts` folder, and change [line number 52](https://github.com/gurnec/btcrecover/blob/master/extract-scripts/extract-bitcoincore-mkey.py#L52) (which is current blank) to this (make sure there are no spaces):
```python
print(base64.b64encode(mkey))
```
Next, run `extract-bitcoincore-mkey.py` as [described in the docs here](https://github.com/gurnec/btcrecover/blob/master/docs/Extract_Scripts.md#usage-for-bitcoin-unlimitedclassicxtcore), and send the results to me at chris@gurneeconsulting.net. (It's probably safe to post the results to this issue, but just to be safe email would be better.)

(No guarantees I'll be able to help, but I'll give it a try.)

**Comment by qasimilyas99** [comment]
How can i install Pywallet on windows 10.

**Comment by gurnec** [comment]
Download the ZIP file from its [GitHub page here](https://github.com/jackjack-jj/pywallet) and extract it and run it pretty much the same way as btcrecover.

**Comment by qasimilyas99** [comment]
After using Bitcoin Core's -salvagewallet feature now my balance showing bitcoin 0.

**Comment by gurnec** [comment]
First off, if you have a lot of value in that wallet: since it appears to be a corrupted file, the *safest* thing to do would be to stop using your hard drive completely and look into hiring a data recovery specialist. If you continue tinkering, you will decrease the chances that a specialist can recover any corrupted data. This is all far beyond the scope of btcrecover (and my expertise) in that case...

If you'd like to keep tinkering anyways, could you try to sign a message in Bitcoin Core (it's in the `File` -> `Sign message...` menu, then choose any address of yours and then click `Sign Message`)? It should ask for your password.

Have you tried the other two options I suggested? Using Pywallet or running the modified version of `extract-bitcoincore-mkey.py` (on the version of your wallet.dat file before you tried `-salvagewallet`)?

I hate to be pessimistic, but it's not looking very hopeful if you have no backups and `-salvagewallet` has failed you...

**Comment by qasimilyas99** [comment]
Yes, I have tried above described method but I'm unable to proceed with Pywallet , I don't know that how to operate it.

Is it method work? If any python developer build GUI software for entering the passwords in bitcoin core where we can change password by entering old password & new password or in transfer tab where bitcoin core asked password for sending balance, Thank You.

**Comment by gurnec** [comment]
The link I posted above ([this one](https://bitcointalk.org/index.php?topic=34028.msg17452093#msg17452093)) goes to a post with the pywallet command you'd need to run to attempt to scan for and recover keys in a corrupted wallet. You'd need to change those two parameters (the one which says where your wallet.dat currently is and the one which says the folder where the recovered wallet should go).

There's no way to know beforehand if your wallet can be recovered... as I said, since `-salvagewallet` failed, it's not promising...

If you're having trouble with it, I'd suggest you make a post in that same thread; the developer of that tool, "jackjack", still checks it on occasion and there are others there who may also be able to help.

**Comment by qasimilyas99** [comment]
I've run this command pywallet.py --dumpwallet > temp.txt
These are results:
		    "mkey": {
        "encrypted_key": "cb2d26e335eea6619167eb0f1b82b37675adc45b3e112933d8fe4b471bff71ca", 
        "nDerivationIterations": 53761, 
        "nDerivationMethod": 0, 
        "nID": 1, 
        "otherParams": "", 
        "salt": "364bfe3d278014bd"

That method discussed here: https://walletrecoveryservices.com/limited/
Please tell me how can now i crack the password, Thank You.

**Comment by gurnec** [comment]
The "encrypted_key" you posted above is 64 letters (32 bytes) long. It should be 96 letters (48 bytes) long. Your wallet file is corrupted, or it was written by a buggy version of Bitcoin Core. I don't know of any buggy version of Bitcoin Core that does this, so it's probably corrupted. It might not be possible to recover.

How sure are you that you remember your password?

**Comment by gurnec** [comment]
Sorry, but I don't understand your question....

**Comment by qasimilyas99** [comment]
I have extracted hash from wallet.dat for password cracking, I'm asking that how can i know that it is not corrupted, I'm pasted here uncompleted hash > $bitcoin$64$cb2d26e335eea661916

**Comment by qasimilyas99** [comment]
I have extracted the hash from wallet.dat with this command > JohnTheRipper/run/bitcoin2john.py Desktop/wallet.dat

**Comment by gurnec** [comment]
That's from JohnTheRipper's bitcoin2john, correct? It shows the same issue. In particular, that 64 should be a 96 if it came from a non-corrupted wallet.

Even if you had your password, your wallet may be too corrupted to recover any funds. It's hard to say... but could you answer this please?

> How sure are you that you remember your password?

**Comment by qasimilyas99** [comment]
I'm not sure, I can provide you wallet.dat file for examine.

**Comment by qasimilyas99** [comment]
Wallet.dat file have 400+ bitcoins.

**Comment by gurnec** [comment]
You can see all of the [test hashes in JtR here](https://github.com/magnumripper/JohnTheRipper/blob/8d7ccaf1815f6dffc140a407d2ff13f71cc09675/src/bitcoin_fmt_plug.c#L87-L95). They all have a `96` after the `$bitcoin$` part. For some reason, your wallet file only has the first 64 letters of the "mkey", the final 32 have been lost/corrupted. This is the real issue....

What are all 5 of the numbers in the $bitcoin$ hash? For example, the full hash looks like this:

    $bitcoin$64$hexhexhex$##$hexhexhex$#####$##$hexhexhex$##$hexhexhex
             ^^           ^^           ^^^^^ ^^           ^^

There are 5 numbers that are between `$` symbols. The first is `64`, what are the other 4? (Don't post any of the other long hex strings).

If you'd rather send them by email, I'm at chris@gurneeconsulting.net.

**Comment by kost123** [comment]
@qasimilyas99 If you manage to salvage an encrypted key and get an extract and want help cracking it, add me on skype petr5476.

**Comment by qasimilyas99** [comment]
I have sent wallet.dat file to chris@gurneeconsulting.net.

**Comment by gurnec** [comment]
For posterity:

I received the wallet.dat (to others reading this issue: please don't send me your wallet.dat files...) and responded back.

I'd rather not go into specifics in the interest of OP's privacy, however I suspect that OP is mistaken about what they think they have or need...

**Comment by kost123** [comment]
I think it might be worth closing then?

**Comment by gurnec** [comment]
I'm still waiting for a response back from OP...

**Comment by qasimilyas99** [comment]
I've sent you response via email, Thank You for your cooperation.

**Comment by shorena** [comment]
hi, it seems this wallet file got some history and was sold at least 4 times. I hope its alright for me to leave this link to bitcointalk here where the accusation is discussed. 
https://bitcointalk.org/index.php?topic=2069077.0

**Comment by kost123** [comment]
Figured something was up, nobody sends a $1million wallet.dat to another person so easy.

**Comment by gurnec** [comment]
This issue seems to have run its course. Further discussion should probably happen over in the bitcointalk thread, so I'll go ahead and close this.

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
