### ISSUE TITLE
Mynxt wallet support

### ISSUE THREAD

**Issue by kost123** [gurnec/btcrecover#89]
I believe its aes-256-cbc but not sure about much else.

**Comment by gurnec** [comment]
Maybe... there are dozens of altcoins out there, and I'd much rather spend my free time working on support for more popular cryptocurrencies such as Ethereum.

**Comment by viladmir2022** [comment]
hi, if you still have wallet problem. I can recover your lost wallet.
I have powerful servers and excellent software that can find any password.
and my fee is only 15-25% of the recovered fund
here is my telegram id: @viladmir2022 and Gmail: walletsrecoveryservice@gmail.com
