### ISSUE TITLE
No tokens or words but a fixed length

### ISSUE THREAD

**Issue by lophesuicire** [gurnec/btcrecover#9]
Hi,

Is there is a way to brute force a password of a fixed length? I am pretty sure it is 8 characters and I am retty sure I mixed special characters, small, capital and numbers. So can I with tool brute force it telling teh tool to only look for 8-10 characters password?

Thanks

**Comment by gurnec** [comment]
Theoretically yes, but practically no, not in a reasonable amount of time, anyways.

26 lowercase letters + 26 uppercase letters + 10 digits + (let's say) 10 specials = 72 different characters.

For an 8 character long password, 72<sup>8</sup> = 722,204,136,308,736 combinations.

On a mid-level quad-core desktop PC, it would take about 50 years to try every combination for an "easy" wallet such as Electrum or MultiBit Classic. For a "hard" wallet (with a good [KDF](https://en.wikipedia.org/wiki/Key_derivation_function#Key_stretching)) such as Bitcoin Core, it'd take about 90,000 years.

For a 9 character long password, it'd take 70x longer than that.

Without a much better idea of what your password was, neither this tool (nor any other) can help, sorry....

**Comment by jaltek** [comment]
Hi @lophesuicire and @gurnec,

just a small side-note to this:

@gurnec is right. The higher the password length, the greater the combinations, but (correct me if I am wrong):

a.) The formula combinations = characters<sup>password length</sup> would be true to passwords of an unknown length. So if you remember your password has a length of x you have _only_ to test the passwords with a length of x ans skip the small ones, right?

b.) The ETA refers to the fact that _all_ combinations are tried. Maybe the password is found in half of the time (depending on the password itself ;))
