### ISSUE TITLE
How can I view attempted passwords

### ISSUE THREAD

**Issue by ztnark** [gurnec/btcrecover#96]
I've created my tokens.txt file, but I'm not sure that it's correct. What's the easiest way to "QA" the attempted passwords (or just a sample)? I've tried simply printing them out in the loop, but it seems that maybe that the print gets cleared by the status bar before it's visible.

**Comment by gurnec** [comment]
*If* I'm understanding your question correctly: remove `--wallet wallet.dat` from the command line, and [add `--listpass`](https://github.com/gurnec/btcrecover/blob/master/TUTORIAL.md#testing-your-config) instead. E.g. on windows:

    C:\python27\python btcrecover.py --listpass --tokenlist tokens.txt | more

or on Linux or OS X:

    ./btcrecover.py --listpass --tokenlist tokens.txt | less

Or if you'd like, post your tokens.txt file (after replacing any sensitive info of course) and I'd be happy to take a look.

**Comment by ztnark** [comment]
This is exactly what I was looking for. Sorry that I missed it in the docs...

**Comment by gurnec** [comment]
No worries. If the docs had a proper table of contents and/or index, you probably wouldn't have missed it...

**Comment by nori19870522** [comment]
I am Japanese and do password analysis.
https://keychainx.io/ 

This is Robert's article.
https://news.bitstarz.com/bitstarz-news-interview-robert-rhodin-keychainx-ceo  

I may be able to find the password you lost. Do you need help with your login?
